### PR TITLE
add BTK to base-goreli and goreli

### PR DESCRIPTION
**Pull request by VivekKadvani**
**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Review by roninjin10 — CHANGES_REQUESTED** [review]
Need to name the svg logo.svg

**Comment by VivekKadvani** [comment]
@roninjin10 changed name to logo.svg

**Comment by hamdiallam** [comment]
heads up @VivekKadvani that goerli is being depreceted this month. You might want to migrate to sepolia

**Comment by hamdiallam** [comment]
Is this token bridged via the canonical bridge?

Based on the contract creation, it doesn't look like an OptimismMintableERC20. If not, please tag as nobridge

**Comment by VivekKadvani** [comment]
> Is this token bridged via the canonical bridge?
> 
> Based on the contract creation, it doesn't look like an OptimismMintableERC20. If not, please tag as nobridge

**Comment by spacesailor24** [comment]
Hey @VivekKadvani, if you're still interested in having this merged, can you provide a response to [this question](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/595#issuecomment-1879387951)?

**Comment by roninjin10** [comment]
Going to close this feel free to reopen

**Pull request closed without merging**
