### PR TITLE
Add Wrapped Tezos (WXTZ) on Optimism Kovan and Mainnet

### PR DESCRIPTION
**Pull request by swetshaw**
**Description**
- Added WXTZ logo to `logos/WXTZ.png`
- Added WXTZ token info for Optimism kovan and mainnet to `optimism.tokenlist.json`
- Sent 100 WXTZ to 0xe3a90926133fef3c58514fA1aAeF75E0998aedD5 on eth kovan for testing

### CODE REVIEW

**Comment by Nicca42** [comment]
Please resolve conflicts

**Comment by swetshaw** [comment]
Hey @Nicca42 , I have resolved the conflicts

**Comment by swetshaw** [comment]
Hi @Nicca42 , the build was successful when run locally, but it's failing here, can you look into it? Or try re-running the build action here

**Comment by smartcontracts** [comment]
Hi! We recently updated our token list to a new v2 system that simplifies the process of adding new tokens and will ultimately speed up the review process. Please refer to our [new README](https://github.com/ethereum-optimism/ethereum-optimism.github.io#adding-a-token-to-the-list) for information about the new process. You may have to close this PR and open a new one instead. Apologies for the inconvenience.

**Comment by smartcontracts** [comment]
Hi! We recently updated our token list to a new v2 system that simplifies the process of adding new tokens and will ultimately speed up the review process. Please refer to our [new README](https://github.com/ethereum-optimism/ethereum-optimism.github.io#adding-a-token-to-the-list) for information about the new process.

Our new token listing process is significantly simplified and makes the steps to add a new token much easier. Since this PR is using the old token listing format, we are closing this PR and would like to ask you to open a new PR with the updated format. Our apologies for the inconvenience here, we're doing our best with the new process to make sure that future token listing PRs get feedback quickly.

**Pull request closed without merging**
