### PR TITLE
Add KITE

### PR DESCRIPTION
**Pull request by piesrtasty**
Add KITE

### CODE REVIEW

**Comment by piesrtasty** [comment]
Not sure what I need to change here?

**Review by annieke — DISMISSED** [review]
can you check your token name? and is it bridged from anywhere?
```
These errors caused the validation to fail:
KITE on chain optimism-goerli token 0xbcc847DdE48E579fa8d98E0d4bd46161A0f84F8A has incorrect name
KITE on chain optimism-goerli token 0xbcc847DdE48E579fa8d98E0d4bd46161A0f84F8A could not fetch l2Bridge or l1Token.
                    This token most likely needs nobridge or a bridge override set.
```

**Comment by piesrtasty** [comment]
@annieke So there are 2 tokens

Optimism Goerli (This is the native token)
Name: Protocol Token
Symbol: KITE
Address: https://goerli-optimism.etherscan.io/address/0xbcc847dde48e579fa8d98e0d4bd46161a0f84f8a

Goerli
Name: KITE
Symbol: KITE
Address: https://goerli.etherscan.io/address/0x1668065ca7e62382fdf4e0cb1fb7cc5154e72aeb

This is a native L2 token that has been bridged from Optimism-Goerli to Goerli. I used the OptimismSDK and the standard bridge to do the following bridge transactions.


Send tokens from L2 -> L1: https://goerli-optimism.etherscan.io/tx/0xe0bc4b545dd9869e2764d0e74da9dbbc539120f9f421f799ca8b016b85f6c17e

Withdraw tokens on L1: https://goerli.etherscan.io/tx/0x80e2dc71cb913e83d800255dec526a71b2c53f22cd5b20077505666eb8e62b3f

Do the tokens neem to have the exact same name? If so, I will need to redeploy the `OptimismMintableERC20` that is deployed to goerli.

I was under the impression that once my token with it's chain addresses is added to this repo I'll be able to use the official optimism bridge app and won't need to do it myself via the sdk and / or etherscan. Is that correct?

**Comment by piesrtasty** [comment]
@annieke Does the above information suffice to merge the PR ?

**Comment by annieke** [comment]
> Do the tokens need to have the exact same name? If so, I will need to redeploy the OptimismMintableERC20 that is deployed to goerli.

@piesrtasty that's a standard we're trying to keep, so please do it! please also run the validation script locally and try to make sure it passes; thank you so much!

**Comment by piesrtasty** [comment]
@annieke okay I have deployed a new token on L1 with the same name. When I try to locally validate I get

```
error: KITE on chain optimism-goerli token 0xbcc847DdE48E579fa8d98E0d4bd46161A0f84F8A could not fetch l2Bridge or l1Token.
                    This token most likely needs nobridge or a bridge override set.
```

The token deployed on optimism-goerli is not the standard L2Token so there will be no l1Bridge or l1Token properly. The token on optimism-goerli is the native token and the StandardL2Token is deployed on goerli.

This is basically the inverse of the config most other projects have. I know the bridge supports this config because there is documentation on it and I've bridged between them multiple times.

Is it possible this repo is not configured to include native L2 tokens?

**Comment by roninjin10** [comment]
Hey @piesrtasty this is a bug in our validation not correctly supporting l2 native tokens. We will look into fixing this

**Comment by roninjin10** [comment]
@piesrtasty actually I misread your issue. If your token does not have an l2Bridge on it it will not work with our l2 bridge I believe. I'm not 100% sure ont his though and will look into this give you an answer and a path forward

**Comment by piesrtasty** [comment]
> 

I manually used the OP Standard L2 Bridge so it definitely works. I included the transactions above.

**Comment by roninjin10** [comment]
Ah I see. Yea so our validation doesn't handle this use case atm and we will need to update validation before we can merge. Apologies for the delays

**Comment by piesrtasty** [comment]
@roninjin10 Oaky cool. Is that currently on the roadmap? Updating the validation to support that? Thanks!

**Comment by piesrtasty** [comment]
@roninjin10 bumping this as it just got marked stale, any eta on supporting this?

Additionally can I conclude that there are 0 tokens that are native to L2 currently in production on Optimism and supported by the bridge in this repo? (Assuming this is the case because you said the repo didn't support merging this)

**Comment by piesrtasty** [comment]
bumping this again as it's been marked stale

**Comment by roninjin10** [comment]
@piesrtasty thanks for bumping looking into this soon

**Comment by piesrtasty** [comment]
@roninjin10 bumping again as it went stale :)

**Comment by roninjin10** [comment]
@piesrtasty can you please verify the l1 contract on etherscan

**Comment by piesrtasty** [comment]
@roninjin10 The L1 contract was deployed using the existing OptimismMintableERC20Factory contract that OP deployed at https://goerli.etherscan.io/address/0x883dcf8b05364083d849d8bd226bc8cb4c42f9c5

This is the deploy transaction https://goerli.etherscan.io/tx/0xaf2496f8ff38d099d43a1575a10ed0a48f3a25ccaab91de11e505ab3c2f4b9ab

I've spent about an hout trying to verify the contract via hardhat and etherscan UI but because I was not the original deployer I am struggling to get the byecode to match.

Any ideas where to go from here?

**Comment by piesrtasty** [comment]
Bumping this to prevent being stale.

**Pull request closed without merging**
