### PR TITLE
Add SBC to Base

### PR DESCRIPTION
**Pull request by chasemerlin**
Add SBC to Base

@roberto-bayardo

### CODE REVIEW

**Comment by GabrielaMelendezQuan** [comment]
Hi @chasemerlin, 

Can you please provide the following information for the [Upgrader role](https://basescan.org/address/0xc1bc0450f8bb1386ffd5150cbb3ad38da1f0dd12#readContract#F8) of the SBC contract:

1. The nature of any multi-sig or other custody setup (# signers required / total signers, or other guarded access). Please provide a link where this can be verified.
2. A claim indicating how many are independent signers (i.e. different individuals) there are - ideally please indicate the addresses of the multisig participants and the associated holder identities for those addresses. If this is not possible, can you please attest that these are separate entities?
3. Whether you use a hardware wallet, and if not where the keys are stored

**Comment by chasemerlin** [comment]
Hi @GabrielaMelendezQuan,

The Upgrader role is held by a 2 of 3 Multi-Party Computation (MPC) wallet `0xb180F98037A63A3dCa66b6B4DdbF250265b65110' managed in Brale's custodial infrastructure. Key shares are encrypted with different keys in separate AWS accounts in different regions in the United States.

Access to these accounts is only available to a user with a specific role. The role can only be granted via a change to our infrastructure as code definitions, which requires multiple individuals to do.

**Comment by chasemerlin** [comment]
Hi @gabririgo is the information provided sufficient?

**Comment by gabririgo** [comment]
> Hi @gabririgo is the information provided sufficient?

not sure you intended to tag me..

**Comment by wbnns** [comment]
ACK

**Comment by wbnns** [comment]
@chasemerlin 

Please accept my sincerest apologies; I'm sorry that you haven't received an update on this PR before today and thanks so much for your patience.

**Review by wbnns — APPROVED** [review]

**Review by wbnns — CHANGES_REQUESTED** [review]
Please redeploy as an OptimismMintableERC20. Once you've done so, we can reopen.

**Comment by wbnns** [comment]
@chasemerlin 

If you'd like, rather than redeploy you could alternatively update this PR to add the `"nonstandard": true,` option to the JSON.

Hope that helps! If you have questions just let us know.

**Comment by wbnns** [comment]
@chasemerlin 

Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

**Pull request closed without merging**
