### PR TITLE
Add Ucash Token to Base

### PR DESCRIPTION
**Pull request by antron3000**
Add UCASH token to BASE (orignally ERC20 on Ethereum)

https://www.coingecko.com/en/coins/ucash

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@antron3000 

Hello, your logo should be named `logo.svg` -- could you please update?

**Comment by antron3000** [comment]
Changed logo name to logo.svg as requested

**Comment by wbnns** [comment]
@an

Thanks for the update. I reran CI/CD and it is now also reporting that the decimals do not match between the two deployed versions:
```
error: UCASH on chain ethereum token 0x92e52a1A235d9A103D970901066CE910AAceFD37 has incorrect decimals
```
Please fix and let us know once updated.

**Comment by antron3000** [comment]
The original token has 8 decimals. Fixed.

**Comment by antron3000** [comment]
Is everything good to go @wbnns ?

**Comment by antron3000** [comment]
Oh I see I need to deploy a new contract. doing now.

**Comment by antron3000** [comment]
@wbnns Created new Token contract with 8 decimals. Should work now.

**Review by wbnns — APPROVED** [review]
ACK

@antron3000 Thanks for the updates and for building on Base 🔵

**Pull request merged**
