### PR TITLE
Add base l2 token address for UNI

### PR DESCRIPTION
**Pull request by westonnelson**
**Description**

Adding UNI - Uniswap - token address deployed on Base L2.

**Additional context**

Pinging @cfluke-cb @wbnns per PR instructions.

### CODE REVIEW

**Comment by wbnns** [comment]
@westonnelson 

Hi there! Thanks for the PR! Are you affiliated with Uniswap?

**Comment by westonnelson** [comment]
Hey there @wbnns ! 

Always happy to contribute to the ETH ecosystem/Base in any way I can.

My only affiliation in this capacity here is as a long-time user of the protocol. 

I noticed the OptimismStandardERC20 L2 token was deployed for UNI on Base, researched to confirm it does in fact map back to the proper address on L1, and figured it would be helpful for users/devs on Base to see the token if it is now live on Base. 

Let me know if there is anything else I could do to help grow Base.

Weston

**Comment by rcbgr** [comment]
hey @westonnelson, are you with Uniswap? If not, we are going to close this PR

**Comment by rcbgr** [comment]
Also, your JSON is invalid. Please correct

**Comment by westonnelson** [comment]
> hey @westonnelson, are you with Uniswap? If not, we are going to close this PR

Greetings @rcbgr. No worries and sounds good. As I mentioned above, no: this PR is not in any affiliation with Uniswap here, I simply noticed the canonical token had been deployed on Base using the official bridge/canonical token bridge, and also that this L2 token is available for bridging using the Rollbridge app from Base to Ethereum and it was unclear to me why someone hadn't submitted the PR for this already. 

So I wanted to contribute here - apologies if this caused any confusion! Please let me know if I can help any further. 

Weston

**Comment by wbnns** [comment]
@westonnelson 

Thanks for the details! Checking into this and will follow-up here as soon as an update is available. 👍

**Comment by wbnns** [comment]
@westonnelson 

Thanks for opening this PR! We're going to defer to #792 since it was opened first.

**Comment by westonnelson** [comment]
Awesome, I'm always glad to help. If anything else is needed, please let me know.

I just reviewed PR 792 you mentioned, looks good to me!

Cheers 🫡

**Pull request closed without merging**
