### PR TITLE
add ether.fi weETH for Base mainnet

### PR DESCRIPTION
**Pull request by solipsis**
add ether.fi weETH for Base mainnet
`mainnet`: https://basescan.org/address/0x4c94DE27c94962Dba6Ebb77924Ac54189db75EFA#code

### CODE REVIEW

**Comment by solipsis** [comment]
tagging @roberto-bayardo as requested in the README

**Comment by roberto-bayardo** [comment]
Getting a validation failure: error: `weETH on chain optimism-goerli token 0x7e7d4467112689329f7E06571eD0E8CbAd4910eE does not exist`

Should be fixable by removing the optimism-goerli section in there if it's not needed (or correcting the token address).

**Comment by solipsis** [comment]
> Getting a validation failure: error: `weETH on chain optimism-goerli token 0x7e7d4467112689329f7E06571eD0E8CbAd4910eE does not exist`
> 
> Should be fixable by removing the optimism-goerli section in there if it's not needed (or correcting the token address).

Hmmm that's weird. It passed validation in the previous PR where it was added. https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/553

And the contract definitely exists on optimism-goerli and has been used https://goerli-optimism.etherscan.io/token/0x7e7d4467112689329f7e06571ed0e8cbad4910ee

**Comment by roberto-bayardo** [comment]
@hamdiallam any ideas why this is failing validation?

**Comment by hamdiallam** [comment]
@roberto-bayardo hmm super strange, i'll give this a look tomorrow morning

**Comment by roberto-bayardo** [comment]
> @roberto-bayardo hmm super strange, i'll give this a look tomorrow morning

any luck?

**Comment by roninjin10** [comment]
@roberto-bayardo @hamdiallam this is failing due to rpc flake. I'm able to repro via running the validation in this codespace https://glorious-lamp-544wrr74r77f46xw.github.dev/ . First 2 times it failed to fetch the token.  Sometimes it failed to get decimals. After 6 tries I got the entire thing to work possibly from the cache being warm now.

**Comment by roninjin10** [comment]
Since I got validation to pass for myself running it in that code space I'm going to force merge this in

**Comment by roninjin10** [comment]
Ooops this is a base pr gonna revert and reopen a pr

**Comment by roninjin10** [comment]
reopened this pr here https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/597

**Pull request merged**
