### PR TITLE
DIMO token on Base and PR Description

### PR DESCRIPTION
**Pull request by robertsolomon**
**Description**

Adding the $DIMO token to Base

@cfluke-cb

### CODE REVIEW

**Review by robertsolomon — COMMENTED** [review]
resubmitting

**Comment by njokuScript** [comment]
Hi @robertsolomon can you please tag @cfluke-cb to the description? Thanks!

**Comment by cfluke-cb** [comment]
@robertsolomon Hi Rob, can you reupload the svg image? It came in as html in the PR

**Comment by robertsolomon** [comment]
> @robertsolomon Hi Rob, can you reupload the svg image? It came in as html in the PR

tried again

**Comment by robertsolomon** [comment]
> > @robertsolomon Hi Rob, can you reupload the svg image? It came in as html in the PR
> 
> tried again

@cfluke-cb i should ask. square or rectangle for the SVG

**Review by cfluke-cb — APPROVED** [review]
Looks good on Base side.

**Review by annieke — APPROVED** [review]

**Pull request merged**
