### PR TITLE
$GCH ON BASE 

### PR DESCRIPTION
**Pull request by BlockedDao**
**Description**
@cfluke-cb 
$GCH is a memecoin on ETH that wishes to have an alternative for lower transaction fees 

**Tests**
No tests, pretty straight forward with a fork.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by BlockedDao** [comment]
@cfluke-cb

**Comment by BlockedDao** [comment]
alternative image: https://svgshare.com/i/14yo.svg

**Comment by BlockedDao** [comment]
> Hi @BlockedDao can you update to your alternative image? Can you modify the website property to be a full uri, e.g.? "website": "https://goochtoken.xyz",
> 
> Can you also add the token to coingecko? warning: GCH on chain ethereum token 0x42379293f2b7a5b379abf54329a8CfdD0E518a9B not found on CoinGecko token list

All those should be completed now.

**Review by wbnns — CHANGES_REQUESTED** [review]
@BlockedDao 

Hi there! Can you please update the SVG? It's not rendering. 
2024-04-26 at 22 29 41@2x

**Comment by BlockedDao** [comment]
> @BlockedDao
> 
> Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

yes i would like to resolve these issues

**Pull request closed without merging**
