### PR TITLE
Add CHI token

### PR DESCRIPTION
**Pull request by dusan-mrsic**
I am reopening PR for CHI token. It is extending IOptimismMintableERC20. Our token USC is the same as this one and it is merged without problems.

### CODE REVIEW

**Comment by dusan-mrsic** [comment]
@wbnns seems like problem is CHI-PROTOCOL folder name and name of token and symbol is CHI. What can I do to pass that validation, because there is already folder named CHI?

**Review by wbnns — CHANGES_REQUESTED** [review]
@dusan-mrsic 

Hello, thanks for this PR. CI/CD is failing with the following error:
```
error: CHI-PROTOCOL on chain base token 0x3b21418081528845a6DF4e970bD2185545b712ba could not fetch l2Bridge or l1Token.
This token most likely needs nobridge or a bridge override set.
```
Could you please fix?

**Comment by dusan-mrsic** [comment]
@wbnns I wrote comments already. Problem is that token symbol and name is: CHI. There is already folder named CHI for some token, so I cannot use it. I wrote CHI-PROTOCOL but it is failing, can you tell me what to do in this situation?

**Comment by wbnns** [comment]
@dusan-mrsic 

Thanks, apologies for misperceiving this if that's the case. Looping in @hamdiallam from the OP team here; let's get some additional feedback.

**Comment by wbnns** [comment]
@dusan-mrsic 

Thanks for your patience while we looked into this! Can you please give the token a unique name so it doesn't collide and then user [per-token overrides](https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides) to revert to the desired name?

**Comment by wbnns** [comment]
@dusan-mrsic 

Since it's been some time and we haven't heard back, I'm closing this PR for now. If you're still interested in pursuing this change, please let us know and we can reopen. 👍

**Pull request closed without merging**
