### PR TITLE
MBLK TOKEN

### PR DESCRIPTION
**Pull request by adijdhv**
**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@adijdhv 

Hello, this PR is failing CI/CD with validation errors. Can you please fix?

**Comment by adijdhv** [comment]
May I know the fixes please?

**Review by wbnns — CHANGES_REQUESTED** [review]
@adijdhv 

Here are the issues this PR is erroring with:
```
error: MBLK on chain ethereum token 0xF47245e9A3Ba3dCa8B004E34afc1290B1d435a52 has incorrect symbol
error: MBLK on chain base token 0xa61BfF072c07F4E65d8204C43FF9CBFB44f425E3 has incorrect symbol
error: MBLK on chain base token 0xa61BfF072c07F4E65d8204C43FF9CBFB44f425E3 has incorrect name
```
Hope that helps clarify. Please let us know when this has been resolved.

**Comment by wbnns** [comment]
@adijdhv 

Hello, since it's been a few days and we haven't heard back, going ahead and closing this PR. If you decide you'd like to pursue these changes, please let us know and we can reopen. 👍

**Review by adijdhv — COMMENTED** [review]
redeployed the token with exact name

**Pull request closed without merging**
