### PR TITLE
feat: Add GTC to token list

### PR DESCRIPTION
**Pull request by QEDK**
**Description**
Add Optimism and Ethereum mainnet GTC to Optimism token list.

### CODE REVIEW

**Review by Nicca42 — APPROVED** [review]
LGTM 👍

**Comment by Nicca42** [comment]
Hey y'all seems like the package-lock is out of date. Can you please rebase master once #86 is in? I will ping you again when it is merged. Thanks! @QEDK

**Comment by Nicca42** [comment]
OK master is up to date. @QEDK please rebase master so we can get this PR in.

**Comment by Nicca42** [comment]
Can you deploy and add a Kovan & OP-Kovan token? CI will not pass till it can validate testnet bridging works. Please also give mint rights to this address on Kovan: 0xd23eb5c2dd7035e6eb4a7e129249d9843123079f

**Review by Nicca42 — CHANGES_REQUESTED** [review]
Please add GTC for Kovan and Optimism Kovan.

**Comment by QEDK** [comment]
> Please add GTC for Kovan and Optimism Kovan.

Thanks, this is WIP, will try to get it pushed ASAP.

**Comment by QEDK** [comment]
> Please add GTC for Kovan and Optimism Kovan.

This should be fixed now. :)

**Comment by Nicca42** [comment]
oof last thing, seems there is a merge conflict, please resolve and we can get you in 💪

**Comment by QEDK** [comment]
> oof last thing, seems there is a merge conflict, please resolve and we can get you in 💪

Done.

**Comment by QEDK** [comment]
@Nicca42 this should be good to go.

**Comment by Nicca42** [comment]
Your [Optimism Kovan token](https://optimistic.etherscan.io/address/0xaf8ca653fa2772d58f4368b0a71980e9e3ceb888) seems like an EOA? Think you might have put in the wrong address.

**Comment by DanieleSalatti** [comment]
> Your [Optimism Kovan token](https://optimistic.etherscan.io/address/0xaf8ca653fa2772d58f4368b0a71980e9e3ceb888) seems like an EOA? Think you might have put in the wrong address.

Hi @Nicca42,
Chiming in since I'm following this for a project I'm working on 🙂

The link you posted seems to be for Optimism, not Optimism Kovan? That same address on [Optimism Kovan](https://kovan-optimistic.etherscan.io/token/0xaf8cA653Fa2772d58f4368B0a71980e9E3cEB888) appears to be the token.

**Comment by DanieleSalatti** [comment]
I'm debugging this, the problem seems to be the casing of the address bridge.

Should be `0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1` and not `0x99c9fc46f92e8a1c0dec1b1747d010903e884be1`.

**Comment by DanieleSalatti** [comment]
Confirmed, after changing that all tests pass locally.

**Review by Nicca42 — APPROVED** [review]

**Pull request merged**
