### PR TITLE
Add eusd

### PR DESCRIPTION
**Pull request by pmckelvy1**
eUSD deployments
mainnet: https://etherscan.io/address/0xA0d69E286B938e21CBf7E51D71F6A4c8918f482F
goerli: https://goerli.etherscan.io/address/0xaCD1E1F368c363287aff0Df4e5eCBa1B0caC3ee3#readProxyContract
base-goerli: https://goerli.basescan.org/address/0xe265fc71d45fd791c9ebf3ee0a53fbb220eb8f75#readContract

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
Thanks for this submission. We'll get back to this after next week when the team is back in the office.

**Comment by roberto-bayardo** [comment]
We'll take a look in the coming week.

**Comment by roberto-bayardo** [comment]
Approved for Base

**Review by roberto-bayardo — APPROVED** [review]

**Review by tremarkley — APPROVED** [review]

**Comment by pmckelvy1** [comment]
@roberto-bayardo @tremarkley it seems /eUSD was removed from the repo.  do you know why? or when? I would like to get it added back in.

**Pull request merged**
