### PR TITLE
Add-TestToken-token

### PR DESCRIPTION
**Pull request by vikagabriel**
**Description**

A PR to add Test token to the Base Token List for testing reasons

### CODE REVIEW

**Comment by vikagabriel** [comment]
Adding @cfluke-cb as reviewer

**Review by wbnns — APPROVED** [review]
~ACK~ (see below comment)

@vikagabriel Thank you for your patience, apologies for the delay 🙏

**Review by vikagabriel — COMMENTED** [review]
Thanks for the review!

**Comment by vikagabriel** [comment]
@wbnns, can You please tell when the PR will be merged ?

**Comment by hamdiallam** [comment]
duplicate of #784?

Also please fix validation script errors

**Comment by wbnns** [comment]
@hamdiallam 

Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

**Pull request closed without merging**
