### PR TITLE
Add cbETH on Optimism Mainnet

### PR DESCRIPTION
**Pull request by KNWR**
**Description**
See title, following up https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/266

### CODE REVIEW

**Comment by KNWR** [comment]
Looks like the validation is failing because this is changing (updating) the data.json for cbETH. In this case, this _is_ the intended behavior.

**Comment by roninjin10** [comment]
Validation is failing beause the website is not set ect.   Last time we merged we force merged.  I don't have permission to force merge but I'll help get this in this week

**Comment by roninjin10** [comment]
I'm going to close thi spr in favor of https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/281 for now

**Comment by KNWR** [comment]
Gratze 🙏

**Pull request closed without merging**
