### PR TITLE
Add EthicHub (ETHIX) token

### PR DESCRIPTION
**Pull request by munikes**
Hi, 

This PR adds EthicHub token => ETHIX on mainnet, sepolia, optimism-sepolia and base-sepolia.

Thank you @all!

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@munikes 

Hello, thanks for your patience. Since this was deployed without using the `OptimismMintableERC20Factory` please add the `"nonstandard": true` option to the JSON.

**Comment by munikes** [comment]
Done!, Thank you very much @wbnns for your effort.

**Review by wbnns — APPROVED** [review]
ACK

**Review by annieke — APPROVED** [review]

**Comment by munikes** [comment]
Thank you very much!, Great job @all

**Pull request merged**
