### PR TITLE
add midcurve token to base l1

### PR DESCRIPTION
**Pull request by bullishpaisa**
Adding midcurve token to base l2 bridge. 

Etherscan: https://etherscan.io/address/0x695fcce8c937735c17e10b0b50bd813a222bbe96

Website: https://midcurve.meme/

### CODE REVIEW

**Review by cfluke-cb — APPROVED** [review]
@bullishpaisa Can you add this token to coingecko?
warning: MIDCURVE on chain ethereum token 0xf61d6953400903aAdb38e733E98E57DCf9DD32B3 not found on CoinGecko token list

**Review by annieke — APPROVED** [review]

**Comment by annieke** [comment]
@bullishpaisa can you rebase your PR, or give mergebot the permissions to do it? See the merge failure message for how 🙂

**Review by wbnns — APPROVED** [review]
ACK

**Review by wbnns — CHANGES_REQUESTED** [review]
@bullishpaisa 

Hello, this PR is now failing CI with the following error and warning:
```
error: final token list is invalid
warning: MIDCURVE on chain ethereum token 0xf61d6953400903aAdb38e733E98E57DCf9DD32B3 not found on CoinGecko token list
```
Could you please resolve?

**Comment by wbnns** [comment]
@bullishpaisa 

Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

**Pull request closed without merging**
