### PR TITLE
fix: add crvUSD data + logo

### PR DESCRIPTION
**Pull request by skellet0r**

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
Is it possible to regenerate the Base token address with the alternate token factory for this one?

**Comment by skellet0r** [comment]
Yes definitely for this one 😅

**Comment by roberto-bayardo** [comment]
> Yes definitely for this one sweat_smile

great, the alt actory is at https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4

**Comment by hamdiallam** [comment]
@skellet0r have you gotten a chance to update the address?

**Comment by skellet0r** [comment]
> @skellet0r have you gotten a chance to update the address?

@hamdiallam updated in 2cedcf2

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
