### PR TITLE
Add CTRAVL token to Metal-l2

### PR DESCRIPTION
**Pull request by tarunbloks**
**Description**

A cross chain token for my upcoming project implements IOptimismMintableERC20 for metal-l2 (mainnet).

**Metadata**

_L1 Contract:_
  Ethereum: [0xF35155E38C8750372ca024a3d1b5cc7174AaaBbC](https://etherscan.io/address/0xF35155E38C8750372ca024a3d1b5cc7174AaaBbC)
  
_L2 Contract :_
  Metal-L2     : [0xF35155E38C8750372ca024a3d1b5cc7174AaaBbC](https://explorer.metall2.com/address/0xF35155E38C8750372ca024a3d1b5cc7174AaaBbC)
  
 _Already listed on Base and Optimism._

### CODE REVIEW

**Comment by tarunbloks** [comment]
Hi @nitaliano @wbnns just checking by if something else needs to be done on this from our end

**Comment by tarunbloks** [comment]
@nitaliano @wbnns just bumping..

**Comment by tarunbloks** [comment]
@wbnns @nitaliano just another gentle bump on this..

**Comment by tarunbloks** [comment]
@wbnns thanks for the update.. much appreciated.

**Comment by nitaliano** [comment]
@tarunbloks sorry with the experience of this. Right now it's kind of the expectation that the OP Labs team is going to be responsible for merging token PRs across the whole superchain which isn't really the case. To make this a better experience for Metal they would need to get a reviewer setup with us like we do with Base.

**Review by nitaliano — APPROVED** [review]

**Comment by tarunbloks** [comment]
alright @nitaliano 
thanks a ton for this!! 🥂

**Pull request merged**
