### PR TITLE
Add ethplus

### PR DESCRIPTION
**Pull request by pmckelvy1**
ETH+ deployments
goerli: https://goerli.etherscan.io/address/0x9828BEA55B91f5eAD1b4520680688C820b5a9Cbd#code
base-goerli: https://goerli.basescan.org/address/0x0994206dfe8de6ec6920ff4d779b0d950605fb53#code
mainnet: https://etherscan.io/address/0xE72B141DF173b999AE7c1aDcbF60Cc9833Ce56a8

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
Thanks for this submission. We'll get back to this after next week when the team is back in the office.

**Comment by roberto-bayardo** [comment]
We'll take a look in the coming week.

**Comment by roberto-bayardo** [comment]
Approved from Base side

**Review by roberto-bayardo — APPROVED** [review]

**Review by tremarkley — APPROVED** [review]

**Comment by pmckelvy1** [comment]
@roberto-bayardo it seems this token was removed. any information on why? can we r-open this pr and add it back?

**Comment by roberto-bayardo** [comment]
> @roberto-bayardo it seems this token was removed. any information on why? can we r-open this pr and add it back?

Afraid not, I'm no longer involved in this repo.

**Comment by pmckelvy1** [comment]
@roberto-bayardo do you know who i could contact?

**Pull request merged**
