### PR TITLE
Add tBTC to Base

### PR DESCRIPTION
**Pull request by nkuba**
**Description**

Add tBTC token data and logo for Base chain.

**Additional context**

tBTC is a decentralized, permissionless Bitcoin bridge.

See: https://docs.threshold.network/applications/tbtc-v2

Tagging @roberto-bayardo for a review. 🙏🏻

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
Can you create overrides for the names so validation will pass?

```
ELIFECYCLE  Command failed with exit code 1.
error: tBTC on chain base token 0x236aa50979D5f3De3Bd1Eeb40E81137F22ab794b has incorrect name
error: tBTC on chain base-goerli token 0x783349cd20f26CE[12](https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/5754825795/job/15604880043?pr=446#step:10:13)e747b1a17bC38D252c9e119 has incorrect name
```

**Comment by nkuba** [comment]
It's updated @roberto-bayardo.

**Comment by ericm-cb** [comment]
Hey team, I have a few quick questions about the Owner key ([0x123694886DBf5Ac94DDA07135349534536D14cAf](https://basescan.org/address/0x123694886dbf5ac94dda07135349534536d14caf) and Guardians:

- How is this key stored (cold, hot)? And is it in a secure facility?
              - Will ownership of this key eventually be given to the DAO?
- How many privileged personnel are required to action this key? I.e. can one single person gain access to this key and use it without further controls?
- What are Threshold's plans for the [Guardians](https://blog.threshold.network/minters-guardians-and-a-strong-tbtc/) beyond just giving them the ability to pause? 
              - Who are the current Guardians/are they themselves decentralized? 

Thank you!

@nkuba

**Comment by nkuba** [comment]
Hey @ericm-cb :wave: Please find the answers below.

> Hey team, I have a few quick questions about the Owner key ([0x123694886DBf5Ac94DDA07135349534536D14cAf](https://basescan.org/address/0x123694886dbf5ac94dda07135349534536d14caf)) and Guardians:
> 
> * How is this key stored (cold, hot)? And is it in a secure facility?
> - Will ownership of this key eventually be given to the DAO?
> * How many privileged personnel are required to action this key? I.e. can one single person gain access to this key and use it without further controls?

Ownership of the token contract on Base has been transferred to the Threshold Council (`0x518385dd31289F1000fE6382b0C65df4d1Cd3bfC`), which is a 6-of-9 multisig.

> * What are Threshold's plans for the [Guardians](https://blog.threshold.network/minters-guardians-and-a-strong-tbtc/) beyond just giving them the ability to pause?

There are no plans to give the Guardians more responsibility.

>  - Who are the current Guardians/are they themselves decentralized?

The Guardians are members of the Threshold and broader DeFi community, see https://forum.threshold.network/t/threshold-tbtc-guardians/500.

Please also see the updated article https://blog.threshold.network/minters-guardians-and-a-strong-tbtc/ section "Future plans", where we mention the alternative path of permissionless minting being implemented.

cc: @dimpar, @pdyraga

**Comment by ericm-cb** [comment]
Thank you @nkuba!

Last question in regards to the council themselves - I can't find information (from the Threshold Forum) about who the current council members are. We don't need to know their exact real identities, but just that they are indeed decentralized themselves (e.g. represent different entities, etc.). Are you able to provide this info? And I'm assuming they also use their own key as part of that multisig?  

Thank you!

**Comment by erdogan** [comment]
Hi @ericm-cb - Keep product lead here. 

Council members add/manage their own private keys. Keep/NuCypher do not store members' private keys. 

cc: @nkuba

**Review by roberto-bayardo — DISMISSED** [review]
Looks good from Base side.

**Review by roberto-bayardo — DISMISSED** [review]

**Review by roninjin10 — DISMISSED** [review]

**Review by roberto-bayardo — APPROVED** [review]

**Review by roninjin10 — APPROVED** [review]

**Pull request merged**
