### PR TITLE
Added THALES token to Base mainnet

### PR DESCRIPTION
**Pull request by danijelthales**
**Description**

Deployed THALES token and added it to the token list.
The token https://basescan.org/address/0x514832a97f0b440567055a73fe03aa160017b990

**Tests**

N.A

**Additional context**

N/A

**Metadata**

N/A

### CODE REVIEW

**Comment by danijelthales** [comment]
Tagging @roberto-bayardo per agreement

**Comment by roberto-bayardo** [comment]
Would you be able to re-generate the L2 token using this contract instead of the default factory?

https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4

We learned that with the default factory token addresses will conflict with Optimism tokens. (For example the one you generated conflicts with SOCKS token on Optimism.)

**Comment by danijelthales** [comment]
> 

Sure, here it is https://basescan.org/address/0xf34e0cff046e154cafcae502c7541b9e5fd8c249#readContract.
Updating the PR.

**Comment by danijelthales** [comment]
Hi @roberto-bayardo, anything else needed on my end to get this merged?

**Review by roberto-bayardo — APPROVED** [review]
thanks looks good.

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
