### PR TITLE
Update data.json to include DHT on Base

### PR DESCRIPTION
**Pull request by taminater**
**Description**

Updating to include DHT token contract on Base

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by taminater** [comment]
@roberto-bayardo

**Comment by roberto-bayardo** [comment]
Same comment here as for MTA: please regenerate the L2 token using the factory listed on our docs to avoid address conflicts:

https://docs.base.org/base-contracts/#l2-contract-addresses

**Review by roninjin10 — CHANGES_REQUESTED** [review]
please regenerate

**Review by roberto-bayardo — APPROVED** [review]

**Comment by roberto-bayardo** [comment]
removing my approval: this still needs the token to be regenerated with the updated factory.

**Pull request closed without merging**
