### PR TITLE
Adding the GRAI token.

### PR DESCRIPTION
**Pull request by 0xfornax**
Adds token data and SVG for Gravita's GRAI token.

### CODE REVIEW

**Review by jakim929 — DISMISSED** [review]

**Comment by jakim929** [comment]
approved! @0xfornax can you merge that latest base branch into your fork to let mergify automatically merge this PR?

**Comment by 0xfornax** [comment]
Done!

**Comment by jakim929** [comment]
@0xfornax  the base branch changed just now (right after you pushed), can you merge it again? sorry about this

**Comment by 0xfornax** [comment]
There you go!

**Review by jakim929 — APPROVED** [review]

**Pull request merged**
