### PR TITLE
Add Mog Coin to Base Chain

### PR DESCRIPTION
**Pull request by MoggersMog**
Mog Coin on Base
This coin Mogs all other coins

[@cfluke-cb](https://github.com/cfluke-cb)

### CODE REVIEW

**Comment by MoggersMog** [comment]
@cfluke-cb we had issues with the logo in .svg format, if it looks bad let us know and we can submit a more flattened version

**Comment by cfluke-cb** [comment]
Hey @MoggersMog , the name and symbol need to match on L1 and L2. Currently the L1 symbol is Mog and L2 symbol is MOG. Can you redeploy with these matching?

**Comment by MoggersMog** [comment]
@cfluke-cb redeployed using Mog on a new L2 contract 0x2da56acb9ea78330f947bd57c54119debda7af71

**Review by cfluke-cb — APPROVED** [review]
Looks good from base side.

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
