### PR TITLE
CTSI - Add Base address and update

### PR DESCRIPTION
**Pull request by colinsteil**
**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by colinsteil** [comment]
Hey @cfluke-cb if I view the file it is rendering correctly, but just clicking in it says invalid image source. Do you see something differently? Thanks for your help on this.

**Comment by colinsteil** [comment]
Hey, just wanted to follow up on this quickly if possible. Thanks a bunch!

**Comment by colinsteil** [comment]
Hey @cfluke-cb all good here? Thank you!

**Review by wbnns — APPROVED** [review]
ACK

@colinsteil Thanks for your patience 🙏

**Review by annieke — APPROVED** [review]

**Pull request merged**
