### PR TITLE
Add Spot token to Base Bridges

### PR DESCRIPTION
**Pull request by brandoniles**
**Description**

Add Spot token to the Base bridges

@roberto-bayardo

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
Seeing a few validation errors after rebasing, could you look into these?

```
error: SPOT on chain base token 0xEfB8A6EFf62b14b82A3197CEa85958C6370E1a94 has incorrect decimals
error: SPOT on chain base-goerli token 0x78b3C724A2F663D11373C4a1978689271895256f has incorrect decimals
error: SPOT on chain base-goerli token 0x78b3C724A2F663D11373C4a1978689271895256f does not match L1 token address
```

**Comment by brandoniles** [comment]
I see a decimals mismatch between L1 & L2

I followed [these instructions](https://github.com/ethereum-optimism/ethereum-optimism.github.io#base-tokens) to generate the Base tokens.

SPOT on ETH mainnet has 9 decimals, but the factories on Base only deploy with 18.

Do you have an alternate way to deploy the tokens for Base with 9 decimals? Or a different factory?

**Comment by roberto-bayardo** [comment]
> I see a decimals mismatch between L1 & L2
> 
> I followed [these instructions](https://github.com/ethereum-optimism/ethereum-optimism.github.io#base-tokens) to generate the Base tokens.
> 
> SPOT on ETH mainnet has 9 decimals, but the factories on Base only deploy with 18.
> 
> Do you have an alternate way to deploy the tokens for Base with 9 decimals? Or a different factory?

Hmm. @nickbalestra can you advise how to proceed here?

**Comment by hamdiallam** [comment]
Hm i believe there was a draft PR up that updated the factory, OptimismMintableERC20 contract such that the decimals could be specified cc @roninjin10.

We should prioritize getting it merged in. However it requirements an on-chain upgrade which will take some time. @brandoniles you should be able to use the changes to deploy the factory and use it to create the L2 token. @roberto-bayardo wdyt? Perhaps we can get a temp deployment of it up to unblock folks that don't follow the 18 decimal representation

**Comment by roberto-bayardo** [comment]
Ok, so if you can share the updated factory code with @brandoniles it sounds like he can deploy the "fixed" factory and then generate a token from that which has the proper decimal setting?  That would work for us.

**Comment by hamdiallam** [comment]
Sounds good @brandoniles i'll share the PR for it as soon as we get a round of feedback on it

**Comment by hamdiallam** [comment]
Hey @brandoniles , the factory and OptimismMintableERC20 contracts in the develop branch of ethereum-optimism/optimism was just updated such that decimals can be sepecified. Here's the associated PR https://github.com/ethereum-optimism/optimism/pull/7182.

I would recommend getting a deployment of the factory up yourself to use to generate the right L2 token. Eventually we'll have the official factories updated

**Comment by brandoniles** [comment]
Thanks @hamdiallam . Do you have an estimated deploy date for the new factory? If it's not too far out, it might be safest to wait for the official one.

**Comment by roninjin10** [comment]
hey @brandoniles it will be a bit. Next planned contract upgrades November 18. There are 2 options:
- Deploy the contract factory and use it
- Simply create an l2 token (interface in optimism repo and can be found in pr @hamdiallam linked) and override decimals
I'm happy to assist with both options if you need any help

**Comment by brandoniles** [comment]
Thanks for the update @roninjin10 

I went ahead and deployed the tokens directly on base and base-goerli. Everything looks ok from my end, but let me know if anything is off.

**Review by roninjin10 — COMMENTED** [review]
lgtm will need approval from base cc @roberto-bayardo

**Comment by roberto-bayardo** [comment]
sorry for the delay taking a look

**Review by roberto-bayardo — APPROVED** [review]
lg!

**Comment by brandoniles** [comment]
Hey @roberto-bayardo, anything we can do to help move this along?

**Comment by roberto-bayardo** [comment]
@roninjin10 can you merge this? I've already approved.

**Review by annieke — APPROVED** [review]

**Pull request merged**
