### PR TITLE
Add MRSMIGGLES to Base

### PR DESCRIPTION
**Pull request by MrsMigglesOnBase**
The needed changes for adding a new token to the list have been done through this pull request for the Base token MRSMIGGLES.

### CODE REVIEW

**Comment by MrsMigglesOnBase** [comment]
I edited the JSON file, apparently there was a superflous comma in it.

**Review by wbnns — CHANGES_REQUESTED** [review]
@MrsMigglesOnBase 

Hello, since this is a native deployment, could you please add `nobridge` as described at the following link?

https://github.com/MrsMigglesOnBase/ethereum-optimism.github.io/tree/master?tab=readme-ov-file#non-bridgable-tokens

If you have any questions or doubts, just let us know. 👍

**Comment by MrsMigglesOnBase** [comment]
I added the nobridge option, thanks for your input!

**Review by wbnns — APPROVED** [review]
ACK

@MrsMigglesOnBase Thanks for the updates and for building on Base 🔵

**Pull request merged**
