### PR TITLE
Add wstETH token on Optimistic Kovan network

### PR DESCRIPTION
**Pull request by Psirex**
**Description**
Add the wstETH token to the token list on the Optimistic Kovan network.

**Additional context**
* The image used for the logo of the token is an SVG and not a PNG.
* Token bridged via custom bridge implementation: https://github.com/lidofinance/lido-l2/tree/main/contracts/optimism.
* 1 wstETH token on Kovan network [`0xa88751C0a08623E11ff38c6B70F2BbEe7865C17c`](https://kovan.etherscan.io/address/0xa88751C0a08623E11ff38c6B70F2BbEe7865C17c) was transferred to the account `0xe3a90926133fef3c58514fA1aAeF75E0998aedD5` for testing.
* To bridge tokens using the `CrossChainMessenger` class from the [@eth-optimism/sdk](https://github.com/ethereum-optimism/optimism/tree/develop/packages/sdk) package, use the `DAIBridgeAdapter`. `StandardBridgeAdapter` will throw the error: "token pair not supported by bridge" on the `supportsTokenPair` method call.

### CODE REVIEW

**Review by roninjin10 — APPROVED** [review]

**Comment by Nicca42** [comment]
Hey y'all please resolve merge conflicts to get merged in!

**Comment by Psirex** [comment]
Hi @Nicca42! Sorry for the delay with the PR update. The bridge contracts were redeployed after the audit finalization, and the `optimism.tokenlist.json` config was updated with new addresses. Test L1 token stayed the same - [`0xa88751C0a08623E11ff38c6B70F2BbEe7865C17c`](https://kovan.etherscan.io/address/0xa88751C0a08623E11ff38c6B70F2BbEe7865C17c). The test account `0xe3a90926133fef3c58514fA1aAeF75E0998aedD5` predeposited with 1 wstETH for re-testing.

**Comment by roninjin10** [comment]
@Psirex can you resolve the merge conflicts and then we can get this in!

**Comment by Psirex** [comment]
Hey, @roninjin10! Fixed. Thank you!

**Pull request merged**
