### PR TITLE
Add base L2 token address for KNC

### PR DESCRIPTION
**Pull request by manhlx3006**
Added KNC token to Base chain

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
Can you please regenerate the L2 token using the factory from our current docs/ instructions? 

https://docs.base.org/base-contracts/#l2-contract-addresses

The old predeploy factory generates tokens with addresses that conflict with others on optimism.

**Comment by roberto-bayardo** [comment]
looks like you'll need to override the names to get them to match and fix these validation failures:

```
error: KNC on chain base token 0x94332448acF26735F1070e277Fb7326A71075D76 has incorrect symbol
error: KNC on chain base token 0x94332448acF26735F1070e277Fb7326A71075D76 has incorrect name
```

**Comment by manhlx3006** [comment]
I have redeployed the KNC token contract using the new l2 contract address, with symbol = KNC and name = Kyber Network Crystal v2

**Review by roberto-bayardo — APPROVED** [review]
Looks good from base side thanks!

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
