### PR TITLE
Add 🇺🇸

### PR DESCRIPTION
**Pull request by ENSpunks**
**Description**

Adding 🇺🇸 to Base

NOTE: because the symbol is an emoji (🇺🇸) I named the repository file "CENT" and added an override to the json - copying what was done for https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/833 

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Review by wbnns — DISMISSED** [review]
@ENSpunks 

Hello, it looks like data.json is malformed, can you please lint/fix?

**Comment by ENSpunks** [comment]
@wbnns I think it was a missing bracket and should be fixed

**Comment by wbnns** [comment]
@ENSpunks Thanks for the updates. Looks like CI/CD is still failing with the following issue:
```
error: CENT on chain base token 0x2fa824bb2e06d6cac7dbab00be37dc0f3d440e8b could not fetch l2Bridge or l1Token.
This token most likely needs nobridge or a bridge override set.
```

**Comment by ENSpunks** [comment]
@wbnns added a "nobridge": true

I think there is still an error: https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/9710635503/workflow

**Review by wbnns — APPROVED** [review]
ACK

@ENSpunks Thanks for the changes and also for building on Base 🔵

**Review by wbnns — CHANGES_REQUESTED** [review]
@ENSpunks 

Hello! Can you please update the permissions on your fork to allow modifcations from maintainers? Your fork needs to be rebased before it can be merged.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by ENSpunks** [comment]
Edits by Maintainers is enabled

**Review by wbnns — APPROVED** [review]

**Pull request merged**
