### PR TITLE
Add wbtc erc20 to mode

### PR DESCRIPTION
**Pull request by ssallam**
**Description**

Add wbtc erc20 on Mode

### CODE REVIEW

**Comment by hamdiallam** [comment]
Hey @ssallam,

Sorry this was closed. Befor re-opening, can you provide wbtc documentation that this is the official contract address to be used on the Mode network?

**Comment by agileurbanite** [comment]
@hamdiallam can you provide clarity here I don't see wbtc official docs in general no where other op chains are listed. Appreciate the help

**Comment by hamdiallam** [comment]
Since anyone can create an L2 version of an L1 token, this is referring to wbtc and respective partners needing to do the deployment and specify the canonical version

**Comment by agileurbanite** [comment]
Got it so just write the address to canonical address on L1?

**Comment by agileurbanite** [comment]
@hamdiallam this is the contract address on L1:
https://etherscan.io/token/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599

A little bit about mode as part of OP superchain here:
https://twitter.com/Optimism/status/1749872693451817188

**Comment by agileurbanite** [comment]
Please let us know what additional information you need to proceed.

**Comment by ssallam** [comment]
Thanks @hamdiallam 
I added information about this token in the top comment/description. You can see this token address in Mode's main docs (link above)

**Comment by agileurbanite** [comment]
@hamdiallam can you re-open this PR?

**Comment by hamdiallam** [comment]
Thanks!

I think there's a bit of a misunderstanding of what I meant. I think we need to clarify the token policy for the Mode network. For example DAI on base/optimism is a custom token deployed by the DAI team, not a token created to us or someone else that wished to bridge DAI.

My confusion is on Mode, if the team wants to take ownership of all canonical token addresses which isn't the case for networks like Optimism or Base, or if y'all want the respective teams (DAI/WBTC/etc) to establish it themselves (per-project)

**Comment by ssallam** [comment]
Thanks @hamdiallam 
We chose to deploy the tokens directly. Initially we take ownership of these tokens.

**Pull request closed without merging**
