### PR TITLE
Add GENE to Base

### PR DESCRIPTION
**Pull request by schoad**
Add the ETH native GenomesDAO GENE token to Base.

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by schoad** [comment]
Adding @cfluke-cb as reviewer.

**Comment by cfluke-cb** [comment]
Hi @schoad can you simplify this PR to only 1 token?

**Comment by schoad** [comment]
> Hi @schoad can you simplify this PR to only 1 token?

Will do asap and ping you again. thanks.

**Comment by schoad** [comment]
updated with https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/771

**Pull request closed without merging**
