### PR TITLE
ZynCoin $ZYN migration to BASE

### PR DESCRIPTION
**Pull request by zynachino**
@cfluke-cb thank you!

We excited to bring ZynCoin to BASE

ZynCoin is a memecoin launched on Ethereum and tradable on Solana as well. We have over 6,000 holders between the two chains and a TG community of over 2,300 people. We hope to add many more by migrating a significant portion of liquidity to BASE. Thank you!

A clear and concise description of the features you're adding in this pull request.

$ZYN token migration for the official ZynCoin project

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

No tests - first migration

Add any other context about the problem you're solving.

N/A

    Fixes #[Link to Issue]

### CODE REVIEW

**Comment by zynachino** [comment]
> fyi the image source is not rendering

Will get that to you and drop it in a comment here shortly. Thanks!

**Comment by zynachino** [comment]
> fyi the image source is not rendering

Does this work for you? Ill drop the jumpshare link and also upload the SVG file

https://jumpshare.com/v/jlYgsw14Sh2Nn9iHPLIQ

Zyn Vector 2024 02 22 (4) SVG

**Comment by zynachino** [comment]
> > fyi the image source is not rendering
> 
> Does this work for you? Ill drop the jumpshare link and also upload the SVG file
> 
> https://jumpshare.com/v/jlYgsw14Sh2Nn9iHPLIQ
> 
> Zyn Vector 2024 02 22 (4) SVG



> fyi the image source is not rendering

Here is another option if those others do not work. Thank you!

https://svgshare.com/i/14yn.svg

**Comment by zynachino** [comment]
> fyi the image source is not rendering

Hi! Just checking in to see if any of the above images/links worked. If not, please let me know! Thank you

**Comment by zynachino** [comment]
@annieke hi! did the new logo links work?

**Comment by ymittal** [comment]
@zynachino you should update the PR and check if the svg loads fine. If it loads fine, the svg is good to go.
image

**Comment by zynachino** [comment]
> @zynachino you should update the PR and check if the svg loads fine. If it loads fine, the svg is good to go. image

Great, I believe I updated it and added the svg in a new file just now. Sorry, not a developer here so this is new territory for me. Let me know! Thanks

**Comment by ymittal** [comment]
delete the old `logo.svg` file and rename your new one to `logo.svg` and I think it should be good. I don't have perms to approve the PR though, so you'll have to wait for @annieke here

**Comment by zynachino** [comment]
> delete the old `logo.svg` file and rename your new one to `logo.svg` and I think it should be good. I don't have perms to approve the PR though, so you'll have to wait for @annieke here
> 
> see [this link](https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#add-a-logo-to-your-folder)

Great, thanks! I believe I corrected the issue.

**Review by cfluke-cb — APPROVED** [review]
Looks good on Base side.

**Comment by ymittal** [comment]
@annieke good to ship?

**Comment by zynachino** [comment]
> @annieke good to ship?

hey @annieke! Just checking in here to ensure things are all squared away on our end. Thank you!

**Review by annieke — APPROVED** [review]

**Pull request merged**
