### PR TITLE
adds optimism address

### PR DESCRIPTION
**Pull request by anthonymartin**
**Description**

This PR adds the POP optimism address

### CODE REVIEW

**Comment by roninjin10** [comment]
Can you verify the l1 contract @anthonymartin

**Comment by anthonymartin** [comment]
@roninjin10 the l1 contract is verified on etherscan. are you looking for something else?

**Comment by anthonymartin** [comment]
I guess it's a similar match, but that's all we have - it was deployed with factory from aragon

**Review by roninjin10 — APPROVED** [review]

**Comment by roninjin10** [comment]
got it.   We will have to force merge this since validation will fail until etherscan api confirms it's verified.

**Comment by anthonymartin** [comment]
it turns out their API says it's already verified if attempting to verify
again.

you can also check this link:
https://sourcify.dev/#/lookup/0xD0Cd466b34A24fcB2f87676278AF2005Ca8A78c4

**Pull request merged**
