### PR TITLE
Add GNOME to Base

### PR DESCRIPTION
**Pull request by schoad**
Add the ETH native GenomesDAO Governance token GNOME to Base.

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by schoad** [comment]
Adding @cfluke-cb as reviewer.

**Comment by schoad** [comment]
@cfluke-cb did I miss something in my two PR?

**Review by cfluke-cb — DISMISSED** [review]
Looks good on Base side.

**Comment by schoad** [comment]
Updated in https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/772.

**Pull request closed without merging**
