### PR TITLE
$BITCOIN on Base

### PR DESCRIPTION
**Pull request by wwlawren**
HarryPotterObamaSonic10Inu (Ticker: BITCOIN) is a endgame of crypto-assets (0 Tax). BITCOIN incentivizes the creation of novel and entertaining meme content. With ownership renounced and Liquidity locked, our robust growing community has taken the lead; we have successfully completed a full audit, an NFT collection, and are exploring partnerships with other tokens in the space, a one-of-a -kind website, and one-of-a-kind merchandise and ecommerce site in the works based on the legendary meme that inspired BITCOIN's creation. Our goal is to create an ecosystem for active community members to meet, collaborate, and share our rich lore (the archive of our token's storied history) with the world.

Ethereum CA: 0x72e4f9F808C49A2a61dE9C5896298920Dc4EEEa9

### CODE REVIEW

**Comment by cfluke-cb** [comment]
Hey @wwlawren The decimals need to match on base. Can you redeploy with decimals set to 8 on base?

**Comment by wwlawren** [comment]
@cfluke-cb working with njokuscript to solve. The Base Migrate automatically fetches the metadata, and uses that data, but the factory contract used in the token doesn't accept decimals yet. Waiting to redeploy the smart contract with his guidance.

**Comment by wwlawren** [comment]
@cfluke-cb updated CA address has been added to the data.json file.

**Review by cfluke-cb — APPROVED** [review]
Looks good on base side.

**Comment by hamdiallam** [comment]
hey @wwlawren, the validation script applies for the OP side as well. Can this be fixed?

**Review by hamdiallam — APPROVED** [review]

**Comment by wwlawren** [comment]
@hamdiallam I have removed the OP CA from the data.json.

**Comment by wwlawren** [comment]
@hamdiallam @cfluke-cb appreciate your time and help with this matter. Have a great weekend.

**Pull request merged**
