### PR TITLE
Add Glo Dollar (USDGLO)

### PR DESCRIPTION
**Pull request by gglucass**
Would like to add Glo Dollar to the token list!

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@gglucass 

Hi there! Thanks for your PR! Currently this is failing CI/CD, please see the following link for tips on how to resolve:
https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#automated-checks

Once updated please let us know and we'll re-review.

**Comment by gglucass** [comment]
Hey @wbnns the error logs are quite unclear but I think I've resolved the issue. Can you rerun the checks? NPM for some reason really doesn't like the state of this package.json

**Comment by gglucass** [comment]
Hi @wbnns - bumping this. Would be great if you can rerun the checks.

**Comment by wbnns** [comment]
@gglucass 

Hi there! Thanks for your patience. Unfortunately this is still failing CI/CD. It looks like the issue may be that your logo doesn't have the correct naming convention. Please see here from the README: https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#add-a-logo-to-your-folder

Once you've updated, please let me know and I'll re-review. 👍

**Comment by gglucass** [comment]
@wbnns apologies for the sloppiness on this on my side! I have renamed the logo file and hope the ci/cd will pass now :-)

**Review by wbnns — CHANGES_REQUESTED** [review]
@gglucass 

Can you also please add the `nonstandard: true` key and value to your metadata?

Context: https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#non-standard-tokens

**Comment by gglucass** [comment]
> @gglucass
> 
> Can you also please add the `nonstandard: true` key and value to your metadata?
> 
> Context: https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#non-standard-tokens

Done!

**Review by wbnns — APPROVED** [review]
ACK

@gglucass Thanks for all of the collaboration on these changes!

@nitaliano All set from the Base side and ready for review on OP. 👍

**Pull request merged**
