### PR TITLE
add RSR.

### PR DESCRIPTION
**Pull request by pmckelvy1**
RSR deployments
base-goerli: https://goerli.basescan.org/address/0xc8058960a9d7e7d81143bdba38d19e6824165932#code
goerli: https://goerli.etherscan.io/token/0xB58b5530332D2E9e15bfd1f2525E6fD84e830307#code
mainnet: https://etherscan.io/token/0x320623b8e4ff03373931769a31fc52a4e78b5d70#code

### CODE REVIEW

**Review by jakim929 — CHANGES_REQUESTED** [review]
Thank you for the PR.

Can you please rename the icon to `icon.png`?

Also requesting approval from @roberto-bayardo as this is bridging to base-goerli.

**Comment by pmckelvy1** [comment]
> Can you please rename the icon to `icon.png`?

renamed it to `logo.png` bc thats what the other folders have

**Comment by jakim929** [comment]
> renamed it to logo.png bc thats what the other folders have
my bad. thanks for the catch

one more thing. It seems like the token names provided in data.json value `"Reserve Rights"` are different from the contract values `Goerli Reserve RSR` and `Base Goerli Reserve RSR`. Can you use [overrides](https://github.com/ethereum-optimism/ethereum-optimism.github.io#per-token-overrides) as specified here?

**Comment by pmckelvy1** [comment]
> one more thing. It seems like the token names provided in data.json value `"Reserve Rights"` are different from the contract values `Goerli Reserve RSR` and `Base Goerli Reserve RSR`. Can you use [overrides](https://github.com/ethereum-optimism/ethereum-optimism.github.io#per-token-overrides) as specified here?

done 👍

**Comment by roberto-bayardo** [comment]
cc: @commitgabe

**Comment by pmckelvy1** [comment]
due to https://github.com/orgs/community/discussions/5634 , i cannot seem to "Allow edits from maintainers" https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by pmckelvy1** [comment]
closed in favor of https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/382

**Pull request closed without merging**
