### PR TITLE
Add WAD to tokenlist

### PR DESCRIPTION
**Pull request by gyrocopter36**
**Description**
In this time we can bridge WAD token from ethereum to optimism  successful.

https://etherscan.io/tx/0x031acc30f45f176dd1568a2de6c29b3112b0a16674ea6db6c97505c9c375df13
https://optimistic.etherscan.io/tx/0xfcbd762555bce6c61304f51d6a79f1d794b5a262c823d3ebeccfb97d2258033e

### CODE REVIEW

**Review by Nicca42 — CHANGES_REQUESTED** [review]
Hello! 
Please rebase master so CI can run. 
Also you need to add the WAD token for Kovan and Optimism Kovan. 
Thanks!

**Comment by gyrocopter36** [comment]
Hello @Nicca42  
thanks for reply,

I have added the WAD token for kovan and optimism kovan.

**Comment by Nicca42** [comment]
This looks great! Just one merge conflict you need to resolve and then this can go in!

**Comment by gyrocopter36** [comment]
@Nicca42  I rebase code successfully.

**Review by Nicca42 — APPROVED** [review]

**Comment by gyrocopter36** [comment]
@Nicca42 I rebase code successfully.

**Pull request merged**
