### PR TITLE
add TRIPS token (tripscommunity.com)

### PR DESCRIPTION
**Pull request by jacmos3**
added TripsCommunity.com (TRIPS) token support

### CODE REVIEW

**Review by Nicca42 — CHANGES_REQUESTED** [review]
Hello! 
Please rebase master so CI can run. 
Also you need to add the TRIPS token for Kovan and Optimism Kovan. 
Thanks!

**Comment by jacmos3** [comment]
Hello @Nicca42 
thanks for reply,
can you tell me if it is everything ok now?

Thank you

**Comment by Nicca42** [comment]
You have a conflict with master, please resolve this

**Comment by jacmos3** [comment]
Hi @Nicca42 ,
Conflicts solved and merge done.

Can you please check is everything is ok now?
Thank you

**Comment by Nicca42** [comment]
This looks great! Last thing is could you please do a test bridge on Kovan to Optimism Kovan. You'll need to send the transaction for the funds leaving Kovan and the funds arriving on Optimism Kovan.

**Comment by jacmos3** [comment]
0x37A.. is correct address (the one on the PR too), but it expects the address 0xce4.. that is an older contract which has been abandouned in favour of 0x37A...


Schermata 2022-06-09 alle 10 42 41

**Comment by smartcontracts** [comment]
Hi! We recently updated our token list to a new v2 system that simplifies the process of adding new tokens and will ultimately speed up the review process. Please refer to our [new README](https://github.com/ethereum-optimism/ethereum-optimism.github.io#adding-a-token-to-the-list) for information about the new process.

Our new token listing process is significantly simplified and makes the steps to add a new token much easier. Since this PR is using the old token listing format, we are closing this PR and would like to ask you to open a new PR with the updated format. Our apologies for the inconvenience here, we're doing our best with the new process to make sure that future token listing PRs get feedback quickly.

**Pull request closed without merging**
