### PR TITLE
Adding COC token to OP and Base

### PR DESCRIPTION
**Pull request by jgabriele321**
**Description**

Looking to add this token (which is currently on mainnet to Base) 

Thank you!

### CODE REVIEW

**Comment by jgabriele321** [comment]
CC @roberto-bayardo

**Comment by roberto-bayardo** [comment]
> CC @roberto-bayardo

doesn't seem this involves Base

**Comment by jgabriele321** [comment]
Hi I'm looking to bridge a token I have on Mainnet to Base. I already created a mapping on OP using OptimismMintableERC20Factory

Is there a similar contract on Base so that I can have a Base contract address for the token?

**Comment by roberto-bayardo** [comment]
> Hi I'm looking to bridge a token I have on Mainnet to Base. I already created a mapping on OP using OptimismMintableERC20Factory
> 
> Is there a similar contract on Base so that I can have a Base contract address for the token?

yes, you'll find the base contract addresses here: https://github.com/base-org/contract-deployments/blob/main/mainnet/addresses.json

**Comment by jgabriele321** [comment]
Thank you, I get a 404 error when following this link. I also am having trouble finding find "contract deployment" in the https://github.com/base-org depositories. Is there a second link I can try?

**Comment by jgabriele321** [comment]
I'm sorry for asking dumb questions

I see this contract here (https://docs.base.org/base-contracts)

"createoptimismmintableerc20"

1. is this the right way to map my OP token to Base?
2.  _remoteToken (address) = OP token address yes? 

After I get a base contract address I'll delete this and submit a new pull request 

Thank you roberto




OptimismMintableERC20Factory
--


<br class="Apple-interchange-newline">


OptimismMintableERC20Factory
--


<br class="Apple-interchange-newline">

**Comment by roberto-bayardo** [comment]
Apologies for the bad link.  Yes that page you found is better and contains the address of the token factory on Base (which is the same address as on optimism since it's as precompile).

remote token should be the token address from the L1.  You can only bridge between the L1 (mainnet) and Base, not between Optimism and Base.

**Comment by jgabriele321** [comment]
Ok I now have my Base contract address I will resubmit a clean pull request thank you for the help.

**Comment by jgabriele321** [comment]
CC @roberto-bayardo

I'm new to Github - if you check now you'll see an updated SVG and a base address. 

Happy to answer any other question / provide other information! 

Thank you for all the help!

**Review by roberto-bayardo — APPROVED** [review]
Looks good from Base side.

**Review by roninjin10 — APPROVED** [review]

**Comment by roberto-bayardo** [comment]
@jgabriele321 apologies but would you mind regenerating the L2 token? (Looks like you've yet to mint any L2 COC).

We learned that default factory tokens will have addresses that conflict with different tokens on Optimism which we'd prefer to avoid. We re-deployed a factory here which will give tokens non-conflicting addresses:

https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4#code

**Pull request merged**
