### PR TITLE
Add USD3 base

### PR DESCRIPTION
**Pull request by pmckelvy1**
**Description**

Add USD3 to the superchain token list.

**Tests**

n/a

**Additional context**

n/a

**Metadata**

n/a

### CODE REVIEW

**Review by wbnns — APPROVED** [review]
ACK

**Review by wbnns — CHANGES_REQUESTED** [review]
@pmckelvy1 

Heya, just wanted to follow back up to confirm the website is indeed correct on this one, too. Thanks!

**Comment by pmckelvy1** [comment]
@hamdiallam @wbnns it seems this token was removed from the repo... any information on why?  can we get it added back?

**Comment by hamdiallam** [comment]
@pmckelvy1, the directory is still showing in master, https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/data/USD3/data.json

I don't think it was removed?

**Comment by pmckelvy1** [comment]
@hamdiallam  i see it now, sorry, confused it with another RToken that is missing.

**Comment by hamdiallam** [comment]
no worries!

**Pull request merged**
