### PR TITLE
Add $SKAI token

### PR DESCRIPTION
**Pull request by proggeramlug**
Add $SKAI token.

Ethereum:
https://etherscan.io/address/0xCF078DA6e85389de507ceeDE0E3d217e457B9d49

Base:
https://basescan.org/address/0xe7399151b688a265f347693d358821a5a8c213ec

### CODE REVIEW

**Review by wbnns — DISMISSED** [review]
ACK

@proggeramlug Thanks for building on Base 🔵

**Comment by hamdiallam** [comment]
Hey @proggeramlug! The validation script is failing for these reasons

> 2024-06-21T16:40:12.4454033Z error: SKAI on chain ethereum token 0xCF078DA6e85389de507ceeDE0E3d217e457B9d49 has incorrect name. Got SkaiToken
2024-06-21T16:40:12.4455401Z error: SKAI on chain base token 0xE7399151B688A265F347693d358821a5A8c213Ec has incorrect name. Got SKAI

Can the names be fixed with the appropriate overrides?

**Comment by proggeramlug** [comment]
@hamdiallam Unfortunately we cannot change the ETH name, it's technically impossible.

I'm fine if the base name will have to be adjusted, just tell me how to do that properly.

**Comment by proggeramlug** [comment]
@hamdiallam Nevermind the message above, found the overrides (confused them with solidity overrides lol)

Please check/validate again, name should be the same now through the overrides.

**Comment by hamdiallam** [comment]
thanks for updating!

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
