### PR TITLE
Add HUNT token to Base

### PR DESCRIPTION
**Pull request by sydneyitguy**
Add HUNT Token on Base

- Website: https://hunt.town
- Description: Hunt Town is a Web3 builders guild where builders come together to contribute to the expansion of Web3 culture and products.
- Twitter: [@steemhunt](https://twitter.com/steemhunt)

Contracts:
- Ethereum: https://etherscan.io/token/0x9aab071b4129b083b01cb5a0cb513ce7eca26fa5
- Base: https://basescan.org/token/0x37f0c2915CeCC7e977183B8543Fc0864d03E064C

### CODE REVIEW

**Comment by sydneyitguy** [comment]
Requesting @cfluke-cb to approve Base token

**Comment by cfluke-cb** [comment]
Hi @sydneyitguy The token name on L1 is not matching.
error: HUNT on chain ethereum token 0x9AAb071B4129B083B01cB5A0Cb513Ce7ecA26fa5 has incorrect name. Got HuntToken
Can L1 and Base have matching names of HuntToken?

**Comment by sydneyitguy** [comment]
@cfluke-cb I just updated the token name **to match** the contract data and **redeployed** the Base token with the new token name.

**Review by cfluke-cb — APPROVED** [review]
Looks good on Base side.

**Review by annieke — APPROVED** [review]

**Comment by sydneyitguy** [comment]
@cfluke-cb I'm exploring whether there is an application form or specific procedures for listing on Base Bridge (https://bridge.base.org/) to enable our holders to conveniently bridge HUNT tokens to the Base network using the most trusted interface. 
We plan to establish about a $1M liquidity pool on Base to expand our token economics and benefit from more affordable and faster transactions on the Base chain.

**Pull request merged**
