### PR TITLE
add SOFI

### PR DESCRIPTION
**Pull request by LzyDou**

### CODE REVIEW

**Review by roberto-bayardo — DISMISSED** [review]
looks good for Base!

**Review by annieke — APPROVED** [review]

**Comment by annieke** [comment]
@LzyDou can you [authorize modification on your head branch](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by LzyDou** [comment]
It's weird, I can't find the option of Allow edits from maintainers.

**Comment by annieke** [comment]
@LzyDou it might be in the RaiFinance org settings, if you can't change that try doing it from your personal account?

**Review by annieke — APPROVED** [review]

**Pull request merged**
