### PR TITLE
Add YFX Token

### PR DESCRIPTION
**Pull request by yfxcom**
**Description**

This PR adds the YFX token to the Superchain Token List on Ethereal and Base networks.

**Token Addresses**

- Ethereum : [0xF55a93b613D172b86c2Ba3981a849DaE2aeCDE2f](https://etherscan.io/address/0xF55a93b613D172b86c2Ba3981a849DaE2aeCDE2f)
- Base : [0x6F74bAf5A0F209609e5826AcBebc90d394830cf7](https://basescan.org/address/0x6F74bAf5A0F209609e5826AcBebc90d394830cf7)

**Tests**

Not Applicable;

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@yfxcom 

Hi there! Thanks for opening this PR! Looks like CI/CD is failing with the following error:
```
[ 'YFX' ]
error: YFX on chain ethereum token 0xF55a93b613D172b86c2Ba3981a849DaE2aeCDE2f has incorrect name. Got YFX
```
Can you please fix? Here's a link to the docs if you need to use an override for the name: https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides

**Comment by yfxcom** [comment]
> @yfxcom
> 
> Hi there! Thanks for opening this PR! Looks like CI/CD is failing with the following error:
> 
> ```
> [ 'YFX' ]
> error: YFX on chain ethereum token 0xF55a93b613D172b86c2Ba3981a849DaE2aeCDE2f has incorrect name. Got YFX
> ```
> 
> Can you please fix? Here's a link to the docs if you need to use an override for the name: https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides

Thanks for reminding. I have  fixed it.

**Comment by yfxcom** [comment]
Any updates, please.

**Review by wbnns — APPROVED** [review]
ACK

@yfxcom Thanks for the updates and for building on Base 🔵

**Pull request merged**
