### PR TITLE
Honey Badger

### PR DESCRIPTION
**Pull request by oldmanwithcoin**
**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by cfluke-cb** [comment]
Hi @oldmanwithcoin the image is currently invalid, can you update to a valid png or svg?

**Comment by oldmanwithcoin** [comment]
> Hi @oldmanwithcoin the image is currently invalid, can you update to a valid png or svg?

Done!

Thank you so much for your time :-)

**Comment by oldmanwithcoin** [comment]
> Hi @oldmanwithcoin the image is currently invalid, can you update to a valid png or svg?

Heyo - just checking up on this again! :-)
I committed a new image that works!
Let me know if there's anything else I need to do.

**Review by wbnns — APPROVED** [review]
ACK

**Pull request closed without merging**
