### PR TITLE
Add FOAM to Optimism

### PR DESCRIPTION
**Pull request by iostat**
**Description**

Adds the [FOAM token](https://www.coingecko.com/en/coins/foam) to the Superchain list with Mainnet and Optimism addresses

ETH Mainnet address: https://etherscan.io/address/0x4946fcea7c692606e8908002e55a582af44ac121
Optimism address: https://optimistic.etherscan.io/address/0x79E6c6b6aABA4432FAbacB30cC0C879D8f3E598e

**Tests**
N/A, deployed to Optimism using the OptimismMintableERC20Factory

**Additional context**

Factory transaction: https://optimistic.etherscan.io/tx/0x6f32bf1880b9e96872b45698323293f388625fbfffa86a0b63b1c5eda0f1ce30

There's another similar PR open for Base waiting on approval -- if this is merged first we can resolve the merge conflict (or vice versa).

### CODE REVIEW

**Comment by iostat** [comment]
It appears that master was failing when this PR was opened, and I'm guessing whatever caused the master failure caused this PR to fail. 

Can we rerun the checks? -- it looks like master is OK now

Thanks!

**Comment by tynes** [comment]
@iostat Could you try rebasing this PR to see if that fixes CI?

**Comment by ryan-foamspace** [comment]
this previous heart PR is breaking the checks can you take a look?
https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/637

**Comment by roninjin10** [comment]
Seeing now that pr has heart as a file name. I don't know if that is breaking stuff or not but either case we want to fix that as it's gross to have a heart as a file name (I'm fine with it being in the token name though)

**Comment by iostat** [comment]
@roninjin10 I think it is breaking stuff -- running `npx validate ... --tokens FOAM` (same command as CI) doesn't print any errors but says final token list is valid, with the following in `validation_results.txt`

```
 [
  {
    "instancePath": "/tokens/0/symbol",
    "schemaPath": "#/properties/symbol/pattern",
    "keyword": "pattern",
    "params": {
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$"
    },
    "message": "must match pattern \"^[a-zA-Z0-9+\\-%/$.]+$\"",
    "schema": "^[a-zA-Z0-9+\\-%/$.]+$",
    "parentSchema": {
      "type": "string",
      "description": "The symbol for the token; must be alphanumeric",
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "minLength": 1,
      "maxLength": 20,
      "examples": [
        "USDC"
      ]
    },
    "data": "❤️"
  },
  {
    "instancePath": "/tokens/0/logoURI",
    "schemaPath": "#/properties/logoURI/format",
    "keyword": "format",
    "params": {
      "format": "uri"
    },
    "message": "must match format \"uri\"",
    "schema": "uri",
    "parentSchema": {
      "type": "string",
      "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
      "format": "uri",
      "examples": [
        "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"
      ]
    },
    "data": "https://ethereum-optimism.github.io/data/❤️/logo.svg"
  },
  {
    "instancePath": "/tokens/1/symbol",
    "schemaPath": "#/properties/symbol/pattern",
    "keyword": "pattern",
    "params": {
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$"
    },
    "message": "must match pattern \"^[a-zA-Z0-9+\\-%/$.]+$\"",
    "schema": "^[a-zA-Z0-9+\\-%/$.]+$",
    "parentSchema": {
      "type": "string",
      "description": "The symbol for the token; must be alphanumeric",
      "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
      "minLength": 1,
      "maxLength": 20,
      "examples": [
        "USDC"
      ]
    },
    "data": "❤️"
  },
  {
    "instancePath": "/tokens/1/logoURI",
    "schemaPath": "#/properties/logoURI/format",
    "keyword": "format",
    "params": {
      "format": "uri"
    },
    "message": "must match format \"uri\"",
    "schema": "uri",
    "parentSchema": {
      "type": "string",
      "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
      "format": "uri",
      "examples": [
        "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"
      ]
    },
    "data": "https://ethereum-optimism.github.io/data/❤️/logo.svg"
  }
]
```

**Comment by hamdiallam** [comment]
There's this open [PR](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/694), I put up late last week that should fix the master branch and let us move forward

**Comment by iostat** [comment]
Hey all -- rebased against master after #694 -- can we rerun checks, hopefully third time's the charm?

Thanks so much!

**Review by hamdiallam — APPROVED** [review]

**Comment by hamdiallam** [comment]
Sorry for the delays! Appreciate the patience

**Comment by iostat** [comment]
🎉 Thanks so much!

**Pull request merged**
