### PR TITLE
Update data.json for USDC sepolia

### PR DESCRIPTION
**Pull request by quanglam2807**
New PR for https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/671

> USDC on EVM testnet has been migrated from goerli towards sepolia in Jan 2024. This is to update the data.json to reflect that.
> 
> **Description**
> 
> USDC on EVM testnet has been migrated from goerli towards sepolia in Jan 2024. This is to update the data.json to reflect that.
> 
> **Tests**
> 
> Verified them through both internal verification and external etherscan verification. Links are here:
> 
> 1. Eth sepolia: https://sepolia.etherscan.io/address/0x1c7d4b196cb0c7b01d743fbc6116a902379c7238
> 2. Base sepolia: https://sepolia.basescan.org/address/0x036cbd53842c5426634e7929541ec2318f3dcf7e
> 3. OP sepolia: https://sepolia-optimism.etherscan.io/address/0x5fd84259d66cd46123540766be93dfe6d43130d7
> 
> **Additional context**
> 
> N/A
> 
> **Metadata**

### CODE REVIEW

**Review by wbnns — APPROVED** [review]
~ACK~ Verifiable here: https://developers.circle.com/stablecoins/docs/usdc-on-test-networks

@quanglam2807 Thank you!

**Comment by hamdiallam** [comment]
Hi @quanglam2807,

It looks like the sepolia deployments do not follow the name "USD Coin" listed in the json file as well as the ethereum deployments, hence the validation script error

Is it possible to fix this with a fresh deployment? Might be hassle on Sepolia. Otherwise an easy fix here is to add an "overrides" section to the sepolia entries, overriding the name to "USDC"

**Comment by wbnns** [comment]
@quanglam2807 

Here's a link with reference to how you can fix the failing CI with an override in the JSON. https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides

**Comment by wbnns** [comment]
@quanglam2807 

Since it's been a while and we haven't heard back, I'm closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

**Pull request closed without merging**
