### PR TITLE
Add 1INCH Token

### PR DESCRIPTION
**Pull request by galekseev**
**Description**

Add 1INCH Token to Optimism and Base bridges

Optimism
https://optimistic.etherscan.io/address/0xAd42D013ac31486B73b6b059e748172994736426
Base
https://basescan.org/address/0x7113370218f31764C1B6353BDF6004d86fF6B9cc

@roberto-bayardo

### CODE REVIEW

**Comment by nickbalestra** [comment]
LGTM. 
Adding @roberto-bayardo for Base

**Comment by roberto-bayardo** [comment]
Apologies for the delay.

Would you be able to regenerate the L2 token using this re-deploy of the token factory?

https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4

Unfortunately the predeploy factory is generating addresses that conflict with different tokens on OP mainnet.

**Comment by galekseev** [comment]
Regenerated 1INCH token using base token factory according to @roberto-bayardo recommendations.

**Review by roberto-bayardo — APPROVED** [review]
looks good thanks!

**Pull request merged**
