### PR TITLE
Add FLI Token

### PR DESCRIPTION
**Pull request by DeFliTeam**
Add FLI token to OP Superchain and BASE @roberto-bayardo

### CODE REVIEW

**Comment by DeFliTeam** [comment]
@annieke @roberto-bayardo is anybody checking these, requested over 2 weeks ago

**Comment by cfluke-cb** [comment]
@DeFliTeam Is this token intended to be bridged? if not, please add nobridge: true
Currently this contract requires multiple mitigations.
Who has mint access? Is this controlled by a a multi-sig? Are the controllers of this multi-sig geographically separated? 
Why is this token pausable?

Are these details publicly documented?

**Comment by DeFliTeam** [comment]
@cfluke-cb Contract is controlled by a multi-sig (https://basescan.org/address/0xee680611F5Dc0c5E176393076615206042Bd6044). Users are based on 3 continents (4 wallets). Pausable due to the use of $FLI as gas token on our L3 (settling to BASE). All details are publicly available at https://defli.xyz/crypto

**Comment by DeFliTeam** [comment]
@cfluke-cb @annieke @roberto-bayardo is it possible for you to assign some dedicated resource to these pull requests? It is taking nearly 2 weeks per review.

**Review by wbnns — CHANGES_REQUESTED** [review]
@DeFliTeam 

Hello, thanks for your patience. Since this was deployed without using the `OptimismMintableERC20Factory` please add the `"nonstandard": true` option to the JSON.

**Comment by DeFliTeam** [comment]
@wbnns this has now been added to the data.json entry. Thanks

**Review by wbnns — CHANGES_REQUESTED** [review]
@DeFliTeam 

Hello, the new addition of the `nonstandard` option is missing a comma on the end, could you please fix?

**Comment by DeFliTeam** [comment]
@wbnns comma added as requested. Thanks

**Review by wbnns — APPROVED** [review]
ACK

**Comment by DeFliTeam** [comment]
@wbnns thanks! Please can you now merge as we wish to deploy liquidity

**Pull request merged**
