### PR TITLE
add TRB networks for base

### PR DESCRIPTION
**Pull request by themandalore**
Adding token addresses for Base, Sepolia, and Base-Sepolia

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@themandalore 

Hi there! Looks like CI/CD is failing with the following issues:
```
error: TRB on chain base-sepolia token 0x896419Ed2E0dC848a1f7d2814F4e5Df4b9B9bFcc has incorrect symbol
error: TRB on chain base-sepolia token 0x896419Ed2E0dC848a1f7d2814F4e5Df4b9B9bFcc could not fetch l2Bridge or l1Token.

This token most likely needs nobridge or a bridge override set.
```
Could you please resolve?

**Comment by themandalore** [comment]
> @themandalore
> 
> Hi there! Looks like CI/CD is failing with the following issues:
> 
> ```
> error: TRB on chain base-sepolia token 0x896419Ed2E0dC848a1f7d2814F4e5Df4b9B9bFcc has incorrect symbol
> error: TRB on chain base-sepolia token 0x896419Ed2E0dC848a1f7d2814F4e5Df4b9B9bFcc could not fetch l2Bridge or l1Token.
> 
> This token most likely needs nobridge or a bridge override set.
> ```
> 
> Could you please resolve?

I just took out the testnet, that's a different kind of token (for testing), so I could see how there could be issues.  But thanks for reviewing it!

**Review by wbnns — CHANGES_REQUESTED** [review]
@themandalore 

Thanks for the updates. Alongside additional review, this does not appear to be a valid ERC-20 token contract. Please let me know if I'm mistaken in some way or if I'm misunderstanding the intention of this PR. Thanks!

**Comment by themandalore** [comment]
> @themandalore
> 
> Thanks for the updates. Alongside additional review, this does not appear to be a valid ERC-20 token contract. Please let me know if I'm mistaken in some way or if I'm misunderstanding the intention of this PR. Thanks!

The one on mainnet or a different network?  I can check again, but they should be good.  We're up on Optimism already and quite a few other networks, so would be shocked if there's any issue with the base token

**Comment by wbnns** [comment]
@themandalore 

Hi there! Thanks for following up! I was referring to the deployment on mainnet -- does it conform to the ERC-20 standard?

**Comment by themandalore** [comment]
> @themandalore
> 
> Hi there! Thanks for following up! I was referring to the deployment on mainnet -- does it conform to the ERC-20 standard?

Yes sir, it's already bridged to Optimism and quite a lot of other chains using the standard wrapper.  It's an old token, but is definitely ERC20

**Comment by themandalore** [comment]
Just checking if that works @wbnns

**Comment by wbnns** [comment]
@themandalore 

Copy, thanks for the additional information. Merging based on the review of the Base only portion of the code addition.

**Review by wbnns — APPROVED** [review]
Thanks for building on Base! 🔵

**Pull request merged**
