### PR TITLE
PRE token (Presearch) for Base

### PR DESCRIPTION
**Pull request by VladimirKlimo**
Added PRE token (Presearch) for Base & Base-Sepolia

tagging @cfluke-cb @annieke for review speed-up, thanks a lot

### CODE REVIEW

**Comment by VladimirKlimo** [comment]
@cfluke-cb @taycaldwell @wbnns
Is there anything else what needs to be done from my side? I am quite unsure what's going on :)
Thanks for answer

**Review by wbnns — CHANGES_REQUESTED** [review]
@VladimirKlimo 

Hi there! Can you please add `"nonstandard": true` to the JSON?

**Comment by vladoklimo** [comment]
@wbnns done ... thanks for helping out

**Comment by VladimirKlimo** [comment]
@wbnns done ... thanks for helping out

**Review by wbnns — APPROVED** [review]
ACK

**Review by annieke — APPROVED** [review]

**Pull request merged**
