### PR TITLE
FE-1362: remove all kovan references

### PR DESCRIPTION
**Pull request by tremarkley**

### CODE REVIEW

**Comment by tremarkley** [comment]
Current dependencies on/for this PR:
* master
  * **PR #299** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/299" target="_blank">Graphite</a> 
    * **PR #300** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/300" target="_blank">Graphite</a> 
      * **PR #301** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/301" target="_blank">Graphite</a> 
        * **PR #302** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/302" target="_blank">Graphite</a> 
          * **PR #303** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303?utm_source=stack-comment).

**Comment by tremarkley** [comment]
Current dependencies on/for this PR:
* master
  * **PR #299** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/299" target="_blank">Graphite</a> 
    * **PR #300** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/300" target="_blank">Graphite</a> 
      * **PR #301** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/301" target="_blank">Graphite</a> 
        * **PR #302** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/302" target="_blank">Graphite</a> 
          * **PR #303** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303?utm_source=stack-comment).

**Review by roninjin10 — APPROVED** [review]
already lgtm.  Happy to review it again

**Comment by tremarkley** [comment]
@tremarkley queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303).

**Comment by tremarkley** [comment]
[Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303) couldn't merge this pull request because a downstack PR #301 failed to merge.

**Comment by tremarkley** [comment]
@tremarkley queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303).

**Comment by tremarkley** [comment]
[Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/ethereum-optimism.github.io/303) couldn't merge this pull request because a downstack PR #302 failed to merge.

**Pull request merged**
