### PR TITLE
Add OPENLOOT token

### PR DESCRIPTION
**Pull request by mferranti**
Add OPENLOOT Token

Sepolia:
https://sepolia.etherscan.io/address/0x51fe233C9c4518A84dc14eF8033d804FAe35a25D

Base Sepolia:
https://sepolia.basescan.org/address/0x9acd8E640636B616844c57569028359e46bEED43

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@mferranti 

Hello, CI/CD is failing on this PR with the following issue:
```
error: OPENLOOT on chain base-sepolia token 0x9acd8e640636b616844c57569028359e46beed43 could not fetch l2Bridge or l1Token.
This token most likely needs nobridge or a bridge override set.
```
Could you please fix?

**Comment by mferranti** [comment]
> @mferranti
> 
> Hello, CI/CD is failing on this PR with the following issue:
> 
> ```
> error: OPENLOOT on chain base-sepolia token 0x9acd8e640636b616844c57569028359e46beed43 could not fetch l2Bridge or l1Token.
> This token most likely needs nobridge or a bridge override set.
> ```
> 
> Could you please fix?

Done! i've added the bridge override for base-sepolia

**Review by wbnns — CHANGES_REQUESTED** [review]
@mferranti 

Thanks for the updates. With the recent change the JSON is not formatted correctly in your `data.json`. Looks like the issue is on Line 17. Can you please fix?

**Comment by mferranti** [comment]
@wbnns it should be ok now! thanks!

**Review by wbnns — APPROVED** [review]
ACK

@mferranti Thanks for the updates and for building on Base 🔵

**Pull request merged**
