### PR TITLE
added TRB

### PR DESCRIPTION
**Pull request by themandalore**
**Description**
Added TRB as a token

### CODE REVIEW

**Comment by smartcontracts** [comment]
Hi, please rename `TRB.png` to `logo.png`: https://github.com/ethereum-optimism/ethereum-optimism.github.io#add-a-logo-to-your-folder

**Comment by themandalore** [comment]
I see that the validation is failiing.  Can't really figure out why....have any idea or way I can fix it?

**Comment by smartcontracts** [comment]
@themandalore it looks like the issue is because the [kovan token](https://kovan.etherscan.io/address/0x7B8AC044ebce66aCdF14197E8De38C1Cc802dB4A#code) has a symbol of `TRBP` instead of `TRB`. If this is the right token and you want to use the symbol `TRB`, please use the [overrides field](https://github.com/ethereum-optimism/ethereum-optimism.github.io#per-token-overrides) for that token to manually set the symbol to `TRB`. Let me know if you have any questions.

**Comment by zainbacchus** [comment]
Hi @themandalore , thanks for your PR!
To be able to merge this we need to rebase this PR, there are two ways to do this:

You rebase your branch/fork against our latest master (although if in the meanwhile something change the same issue will emerge gain.
Mergify needs the author permission to update the base branch of the pull request.
https://github.com/GammaStrategies needs to [authorize modification on its head branch](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
If you do https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/2, our system should be able to automatically update this PR so that we can merge it.

Let me know if this helps!

**Pull request closed without merging**
