### PR TITLE
Add Flux blockchain

### PR DESCRIPTION
**Pull request by blondfrogs**
Adding flux folder

BASE: https://basescan.org/address/0xb008BDCF9CdFf9da684a190941dC3dCa8C2Cdd44
ETH: https://etherscan.io/address/0x720CD16b011b987Da3518fbf38c3071d4F0D1495

### CODE REVIEW

**Review by roberto-bayardo — APPROVED** [review]
looks good!

**Comment by roberto-bayardo** [comment]
whoops noticed this isn't passing validation.  Is this a native L2 contract or is it bridged in some unusual way?

**Comment by blondfrogs** [comment]
> whoops noticed this isn't passing validation.  Is this a native L2 contract or is it bridged in some unusual way?
> 
> 

This is a native L2 contract.

**Comment by roberto-bayardo** [comment]
thanks, please add a "nobridge" tag to get validation to pass?

**Comment by blondfrogs** [comment]
@roberto-bayardo I believe only our team will be able to add labels to PR's submitted to your repo.

**Review by roberto-bayardo — DISMISSED** [review]

**Comment by blondfrogs** [comment]
@roberto-bayardo Updated. Thanks

**Review by roberto-bayardo — APPROVED** [review]
good to go!

**Review by roninjin10 — APPROVED** [review]

**Pull request merged**
