### PR TITLE
Add PAW coin

### PR DESCRIPTION
**Pull request by sidrun69**
Add wPAW coin (ETH + Base)

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@sidrun69 

Hi there! Thanks for opening this PR. It looks like the JSON is invalid, with a trailing comma in the `tokens` object -- could you please fix?

**Comment by wbnns** [comment]
@sidrun69 

Thanks for the updates. Unfortunately it appears there are still a couple of issues:
```
error: WPAW on chain ethereum token 0xc11158c5da9db1d553ed28f0c2ba1cbedd42cfcb has incorrect name. Got Wrapped PAW
error: WPAW on chain base token 0xc11158c5da9db1d553ed28f0c2ba1cbedd42cfcb has incorrect name. Got Wrapped PAW
```
The name here should match what is onchain. If you want it to be different, you can override it as described here:
https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides

Hope that helps clarify!

**Comment by wbnns** [comment]
@sidrun69 

Thanks! Apologies, it seems CI is still failing here. Looking into the issue with the OP team.

**Comment by wbnns** [comment]
@hamdiallam @nitaliano

Can one of you please check CI on this one when you have a chance? I'm not seeing any issue locally.

**Comment by nitaliano** [comment]
hey @sidrun69 thanks for the PR! would you mind rebasing this we had a revert on the `master` branch recently and I believe that this will help get the validation script working

**Comment by nitaliano** [comment]
yes it is, thank you for updating it so fast and sorry about the issue you ran into!

**Review by wbnns — APPROVED** [review]
ACK

@sidrun69 Thanks for all of the updates and for building on Base! 🔵

**Pull request merged**
