### PR TITLE
Add dai erc20 to mode

### PR DESCRIPTION
**Pull request by ssallam**
Add dai erc20 to mode

### CODE REVIEW

**Comment by ssallam** [comment]
@hamdiallam this is a replacement for the old pr: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/604

**Comment by roninjin10** [comment]
This pr needs to be rebased

**Comment by ssallam** [comment]
@roninjin10 why is a rebase necessary?

**Comment by ssallam** [comment]
@hamdiallam @roninjin10 rebase is completed, can you please approve/merge.

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
