### PR TITLE
feat-add-mugloo-base-metall2

### PR DESCRIPTION
**Pull request by raahulrathore**
**Description**

A cross chain token for my upcoming project for OpStack.
- Already listed for Optimism.

L1 Contract:
Ethereum: [0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6](https://etherscan.io/address/0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6)

- L2's 
Base:[0xE009e453Ac69B0E9602BA091D5331B31B03D3039](https://base.blockscout.com/address/0xE009e453Ac69B0E9602BA091D5331B31B03D3039)

Metall2:~[0xf1F9Ccc7638F124c3d9354Be0edE2ACb5F0A15Bc](https://explorer.metall2.com/address/0xf1F9Ccc7638F124c3d9354Be0edE2ACb5F0A15Bc)~

going with Base for now as per below thread, will raise a new one for Metall2

### CODE REVIEW

**Comment by nitaliano** [comment]
@raahulrathore thanks for the PR! metal isn't supported yet in this repo if you would like to add it as part of your PR you can follow the steps that this PR did to add a new chain https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/906/files?file-filters%5B%5D=.md&file-filters%5B%5D=.ts&show-viewed-files=true

**Comment by raahulrathore** [comment]
thanks for the update @nitaliano!
I'd then remove the metal from this PR and will get in touch with them for the changes,
so for now, will be going with Base only.

**Comment by raahulrathore** [comment]
@nitaliano updated the PR,
only going with Base as of now, will add metal in another PR.
Thanks!

**Review by nitaliano — APPROVED** [review]

**Comment by wbnns** [comment]
Hi @raahulrathore, thanks for building on Base! Apologies, it looks like there is an issue with your PR in that the source code on the token contract you deployed on Base isn't verified.

Can you please verify it and follow-up here? We may need you to open a new PR, sorry about that.

**Comment by raahulrathore** [comment]
Hi @wbnns, sure 
lemme go through the comments on #922 and raise a new one as requested.

**Comment by raahulrathore** [comment]
Hi @wbnns @nitaliano 
Here is the follow up PR #925 catering the comments

**Comment by squdgy** [comment]
> @raahulrathore thanks for the PR! [metal](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/mainnet/metal.toml) isn't supported yet in this repo if you would like to add it as part of your PR you can follow the steps that this PR did to add a new chain https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/906/files?file-filters%5B%5D=.md&file-filters%5B%5D=.ts&show-viewed-files=true

@nitaliano I'm from the Metal L2 team, and I put up this PR to add our chain (and testnet): https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/932

**Comment by squdgy** [comment]
> > @raahulrathore thanks for the PR! [metal](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/mainnet/metal.toml) isn't supported yet in this repo if you would like to add it as part of your PR you can follow the steps that this PR did to add a new chain https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/906/files?file-filters%5B%5D=.md&file-filters%5B%5D=.ts&show-viewed-files=true
> 
> @nitaliano I'm from the Metal L2 team, and I put up this PR to add our chain (and testnet): #932

@raahulrathore Metal L2 chain is now available if you care to put up a pr for that chain.

**Comment by raahulrathore** [comment]
> > > @raahulrathore thanks for the PR! [metal](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/mainnet/metal.toml) isn't supported yet in this repo if you would like to add it as part of your PR you can follow the steps that this PR did to add a new chain https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/906/files?file-filters%5B%5D=.md&file-filters%5B%5D=.ts&show-viewed-files=true
> > 
> > 
> > @nitaliano I'm from the Metal L2 team, and I put up this PR to add our chain (and testnet): #932
> 
> @raahulrathore Metal L2 chain is now available if you care to put up a pr for that chain.

Big Thanks @squdgy!! Will be raising

**Comment by raahulrathore** [comment]
Hi @pbatmetal, @nitaliano, @wbnns, @squdgy. raised a PR #944 for Metall2, which got merged yesterday. but i still cant see my token on superbridge under Metall2 Mainnet, can someone please help me finding where is the gap

image

**Comment by nitaliano** [comment]
We don't run the bridge FEs it might be best to leave a support issue with them to see if theres anything they are doing on top of the tokenlist where it might not be getting surfaced.

I looked at the tokenlist json to verify and your token is in it
```
{
  "chainId": 1750,
  "address": "0xf1F9Ccc7638F124c3d9354Be0edE2ACb5F0A15Bc",
  "name": "Mugloo",
  "symbol": "MUGLOO",
  "decimals": 4,
  "logoURI": "https://ethereum-optimism.github.io/data/MUGLOO/logo.svg",
  "extensions": {
    "metall2BridgeAddress": "0x4200000000000000000000000000000000000010",
    "opListId": "extended",
    "opTokenId": "MUGLOO"
  }
},
```

**Comment by raahulrathore** [comment]
> We don't run the bridge FEs it might be best to leave a support issue with them to see if theres anything they are doing on top of the tokenlist where it might not be getting surfaced.
> 
> I looked at the tokenlist json to verify and your token is in it
> 
> ```
> {
>   "chainId": 1750,
>   "address": "0xf1F9Ccc7638F124c3d9354Be0edE2ACb5F0A15Bc",
>   "name": "Mugloo",
>   "symbol": "MUGLOO",
>   "decimals": 4,
>   "logoURI": "https://ethereum-optimism.github.io/data/MUGLOO/logo.svg",
>   "extensions": {
>     "metall2BridgeAddress": "0x4200000000000000000000000000000000000010",
>     "opListId": "extended",
>     "opTokenId": "MUGLOO"
>   }
> },
> ```

sure @nitaliano, thanks for the response, will check with them.

**Pull request merged**
