### PR TITLE
Add ankrETH, cSTONE, weETH and DOLA erc20 to mode

### PR DESCRIPTION
**Pull request by agileurbanite**
**Description**

Adding the following erc20s to mode network:

ankrETH
cSTONE
weETH
DOLA

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by agileurbanite** [comment]
FYI @annieke @hamdiallam @wbnns

**Comment by wbnns** [comment]
@agileurbanite 

Thanks for the PR and tag! Will yield to the Mode DRI here.

**Comment by hamdiallam** [comment]
hey @ssallam who is the DRI for mode PRs?

**Review by nitaliano — CHANGES_REQUESTED** [review]
There is a `yarn.lock` in this PR as well, you might have accidentally installed with yarn instead of pnpm. If we're going to go forward with this PR it would be great if we can get this updated to remove it.

**Comment by nitaliano** [comment]
Going to close this out since it's been open for awhile. Feel free to reopen this if you do want to proceed and get this merged!

**Pull request closed without merging**
