### PR TITLE
Add BTRST

### PR DESCRIPTION
**Pull request by musnit**
**Description**

Add BTRST token

**Tests**

Manually tested bridging the token across. Worked.

### CODE REVIEW

**Comment by nickbalestra** [comment]
Adding @roberto-bayardo for the base part

**Comment by roberto-bayardo** [comment]
Would you be able to regenerate the L2 token using this re-deploy of the token factory? 

https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4

Unfortunately the predeploy factory is generating addresses that conflict with different tokens on OP mainnet.

**Review by roninjin10 — APPROVED** [review]

**Comment by roninjin10** [comment]
Looks good from OP side

**Comment by roninjin10** [comment]
do-not-merge til base approval

**Comment by musnit** [comment]
> Would you be able to regenerate the L2 token using this re-deploy of the token factory?
> 
> https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4
> 
> Unfortunately the predeploy factory is generating addresses that conflict with different tokens on OP mainnet.

I've redeployed and commited the new address. Could you provide a link/more documentation to more context/conversation/ around the issue with the precompile is and why a new factory is needed so I can verify that?

**Comment by roberto-bayardo** [comment]
> I've redeployed and committed the new address. Could you provide a link/more documentation to more context/conversation/ around the issue with the precompile is and why a new factory is needed so I can verify that?

It's noted in the README under "base tokens" for this repo: https://github.com/ethereum-optimism/ethereum-optimism.github.io/

We're working to get the default factory updated. The alt-factory is a stop-gap solution.

**Review by roberto-bayardo — APPROVED** [review]

**Review by annieke — APPROVED** [review]

**Pull request merged**
