### PR TITLE
Create USD-plus

### PR DESCRIPTION
**Pull request by maximlafe**
**Description**
A clear and concise description of the features you're adding in this pull request.

**Additional context**
Add any other context about the problem you're solving.

**Metadata**
- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by roninjin10** [comment]
We don't allow special characters in folder name.  Can you change it to usd-plus possibly?

**Comment by nickbalestra** [comment]
Hey @maximlafe , wanted to follow up on this, to make sure you saw the comments! Happy to land this PR after the requested changes (change folder name to usd-plus or similar without using special characters) - thanks you!

**Comment by maximlafe** [comment]
@nickbalestra, sorry for the late reply. Yep, let's change the name to usd-plus.

**Comment by roninjin10** [comment]
@maximlafe we need to change this folder name not the pr title 
image

**Comment by roninjin10** [comment]
The name and symbol are both fine only the folder name is a problem

**Comment by maximlafe** [comment]
@roninjin10 sorry again, file changed

**Comment by roninjin10** [comment]
I did a commit removing the space from `usd plus` but it looks like you don't have the files and logo setup.

Please name the folder `USDplus` with no space, put a file in the folder called `data.json` with your token info and make sure to add a logo.   Here is an example of a pr you can use as example https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/230/files

**Comment by nickbalestra** [comment]
Hey @maximlafe let me know if you need any help with this, otherwise we'll be closing this PR tomorrow and feel free to reopen one following the guidelines!

**Comment by maximlafe** [comment]
@nickbalestra hey, I appreciate your help. I'm not so familiar with GitHub (since I'm not a dev guy), and I'm stuck in creating folders and files (json+logo).

**Comment by roninjin10** [comment]
@maximlafe might be easiest if you start from a fresh or actually.  You need to add your folder with no special characters, a data.json file, and a logo

**Comment by nickbalestra** [comment]
@maximlafe can you share in here in a comment all the info and the logo for the token, so I can help and put up a PR for you

**Comment by maximlafe** [comment]
@nickbalestra thank you!

**Info**
   "name": "USD+",
   "symbol": "USD+",
   "decimals": 6,
   "description": Overnight Finance is an Asset Management Protocol offering Low-Risk Passive Yield Products primarily for
conservative stablecoin investors, both individuals and protocol treasuries. The protocol aspires to be the
'Vanguard of DeFi' whose product range includes USD+ – DeFi equivalent of the money market, ETS – delta-neutral strategies, and Insurance.
   "website": "https://overnight.fi,
   "twitter": "@overnight_fi",
   "nobridge": true,
   "tokens": {
     "optimism": {
       "address": "0x73cb180bf0521828d8849bc8CF2B920918e23032"

**Logo**
https://static.debank.com/image/op_token/logo_url/0x73cb180bf0521828d8849bc8cf2b920918e23032/bd9cf757caca4a4ba38bd54d757638cc.png

**Comment by nickbalestra** [comment]
Hey @maximlafe, thank you! I've opened a PR at #238 - Closing this in favor of that, please follow-up on #238 instead :)

**Pull request closed without merging**
