### PR TITLE
RFKJ Token on Base

### PR DESCRIPTION
**Pull request by RFKBasedDev**
**Description**

Addding RFKJ token to token list. 

**Tests**

None

**Additional context**

PR created with https://www.base-migrate.xyz

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by RFKBasedDev** [comment]
@cfluke-cb I created this PR with base migrate and it was requested there to add you as reviewer. However I do not have permission to add reviewers on the PR.

**Review by wbnns — CHANGES_REQUESTED** [review]
@RFKBasedDev 

Hi there! Thanks for your patience. The latest commit is failing CI / validation; could you please fix?

**Comment by wbnns** [comment]
@hamdiallam

Heya! Do you know what's going on w/ this one? I'm having a little trouble parsing the output of the validation script.
```
error: RFKJ on chain base token 0x54a65B16D18527160FAFC6FCfEBAeD47c2976dfA could not fetch l2Bridge or l1Token.
This token most likely needs nobridge or a bridge override set.
```
I'm able to reference both the L1 and L2 ERC-20s:
+ [ETH](https://etherscan.io/token/0xF64265e65c4529879a7ABf467E00D39E39C0B0DA#code)
+ [Base](https://basescan.org/token/0x54a65B16D18527160FAFC6FCfEBAeD47c2976dfA#code)

**Comment by wbnns** [comment]
@RFKBasedDev 

Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

**Pull request closed without merging**
