### PR TITLE
Add WEXO token

### PR DESCRIPTION
**Pull request by komo81**
Add WEXO token to the list.

Ethereum:
https://etherscan.io/token/0xf31698DDAd0d11160Fe85c500397A470CD3d492E

Base:
https://basescan.org/token/0xac12f930318be4f9d37f602cbf89cd33e99aa9d4

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@komo81 

Hello, the deployed token on Base doesn't match the byte code for the [OptimismMintableERC20 Factory](https://basescan.org/address/0xF10122D428B4bc8A9d050D06a2037259b4c4B83B).

Could you please update your PR using the above factory?

**Comment by komo81** [comment]
Hi @wbnns,

I don't understand your comment. You can see here https://basescan.org/token/0x1287A235474E0331C0975e373bdD066444d1Bd35#code that the token is OptimismMintableERC20. It looks exactly the same as e.g. this token https://basescan.org/token/0x1287A235474E0331C0975e373bdD066444d1Bd35#code you've approved here https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/846. We deployed our token using this tool https://supermigrate.xyz/en/base/migrate so I suppose everyting is ok.

**Comment by komo81** [comment]
We also have approved (merged) [PR here](https://github.com/superbridgeapp/token-lists/pull/57) into superbridgeapp, so there must be everyting ok. Is it sill not ok for you?

**Comment by wbnns** [comment]
@komo81 Thanks for clarifying! Apologies, it was not clear in the initial review that this was the case.

**Review by wbnns — APPROVED** [review]
ACK

**Review by annieke — APPROVED** [review]

**Pull request merged**
