### PR TITLE
Add UNION token

### PR DESCRIPTION
**Pull request by eddynockk**
Add UNION (UNION Protocol/UNIONFinance) token 

Website project: https://app.union.finance/
Twitter: @unionprotocol
Bridge OpUNION (Optimism) to UNION (Ethereum)

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@eddynockk 

Hi there! It looks like CI on this PR is failing with the following error:
```
error: UNION on chain optimism token 0xB025ee78b54B5348BD638Fe4a6D77Ec2F813f4f9 has incorrect symbol
```

**Comment by eddynockk** [comment]
> @eddynockk
> 
> Hi there! It looks like CI on this PR is failing with the following error:
> 
> ```
> error: UNION on chain optimism token 0xB025ee78b54B5348BD638Fe4a6D77Ec2F813f4f9 has incorrect symbol
> ```

They definitely go together, but I don't understand what to replace with Symbol at the beginning or in overrides. if  optimistism, with the OpUNION prefix :(

**Comment by wbnns** [comment]
@eddynockk 

Heya, looks like there are still some validation errors coming through:
```
error: UNION on chain ethereum token 0x5Dfe42eEA70a3e6f93EE54eD9C321aF07A85535C has incorrect name. Got Union Token
error: UNION on chain optimism token 0xB025ee78b54B5348BD638Fe4a6D77Ec2F813f4f9 has incorrect name. Got Optimism UNION
```
You can use overrides to fix, as described here:
https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides

Hope that helps!

**Review by wbnns — CHANGES_REQUESTED** [review]
@eddynockk 

Heya! Just a friendly bump that there's still an issue with CI failing.

Details here: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/840#issuecomment-2151166622

**Comment by wbnns** [comment]
@eddynockk 

Since it's been some time and we haven't heard back, closing this PR for now. If you'd still like to pursue the change, please let us know and we can reopen. 👍

**Pull request closed without merging**
