### PR TITLE
Add Cryptex token to Base

### PR DESCRIPTION
**Pull request by crisgarner**
**Description**

Added CTX token to Base

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@crisgarner 

Hi there! It looks like the name doesn't match the actual onchain token name on Ethereum and Base. Can you please fix?
```
error: CTX on chain ethereum token 0x321c2fe4446c7c963dc41dd58879af648838f98d has incorrect name. Got Cryptex
error: CTX on chain base token 0xBB22Ff867F8Ca3D5F2251B4084F6Ec86D4666E14 has incorrect name. Got Cryptex
```

**Comment by crisgarner** [comment]
Fixed! @wbnns

**Comment by voith** [comment]
@wbnns Can you please take a look at this PR?

**Review by wbnns — APPROVED** [review]
@crisgarner @voith 

Thanks for the updates and for building on Base!

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
