### PR TITLE
wPOKT on Base

### PR DESCRIPTION
**Pull request by mehrdadmms**
**Description**

Add the wPOKT Token to the token list for Base bridge.

### CODE REVIEW

**Comment by nodiesBlade** [comment]
@cfluke-cb  @taycaldwell @wbnns , please take a look.

**Review by cfluke-cb — CHANGES_REQUESTED** [review]
Can the names and decimals match on Base? 

error: wPOKT on chain ethereum token 0x67f4c72a50f8df6487720261e188f2abe83f57d7 has incorrect decimals
error: wPOKT on chain ethereum token 0x67f4c72a50f8df6487720261e188f2abe83f57d7 has incorrect name. Got Wrapped Pocket

**Comment by mehrdadmms** [comment]
@cfluke-cb Thank you, please check again updated the decimal to 6 and name to the correct value.

**Review by wbnns — APPROVED** [review]
ACK

**Comment by studna** [comment]
@mehrdadmms don't you need to re-deploy Base contract with decimals = 6 as well?

**Comment by mehrdadmms** [comment]
@studna I don't think so. 
image
The interface only accepts token address, name and symbol.

**Review by wbnns — CHANGES_REQUESTED** [review]
@mehrdadmms 

Indeed, as @studna mentioned (thanks for flagging), the decimals should match. You can redeploy using this tool: https://www.base-migrate.xyz/

**Comment by mehrdadmms** [comment]
@wbnns Thank you and sorry for the inconvenience. I redeployed it using the mentioned link.

**Review by wbnns — DISMISSED** [review]
@mehrdadmms 

Thanks for the updates! Can you please remove logo.svg and rename `POKT.svg` to `logo.svg`?

**Comment by mehrdadmms** [comment]
For sure. It is done!

**Review by wbnns — COMMENTED** [review]
ACK

@mehrdadmms Thanks for building on Base 🔵

**Review by wbnns — APPROVED** [review]

**Pull request merged**
