### PR TITLE
Add BURN to Base Chain

### PR DESCRIPTION
**Pull request by realshibadoge**
Add Burn Token on Base

Burn: https://www.deflationary.com/
Ethereum: 0xa2fe5e51729be71261bcf42854012827bc44c044
Base: 0x3bd3b0eaea951cc4cb05be2234eb8bc953726e08

### CODE REVIEW

**Comment by realshibadoge** [comment]
> Hi @realshibadoge , can you describe how the blacklisted bot list is maintained? Currently this allows the owner to essentially hold a wallet addresse's erc20 balance. How could an individual challenge being on that list?

Sure. Simply put, we don't maintain it. The function is mostly broken due to a logical error in our contract, and as a result it has never been used.

```
        require(
            !_isBlackListedBot[from] || !_isBlackListedBot[to],
            "You are blacklisted"
        );
```

The operation will continue if: 
* Both from and to are not blacklisted.
* One of from or to is blacklisted but the other is not.


This would require both addresses to be blacklisted, so anyone could generate another address if we were malicious, and transfer their tokens out.

**Comment by realshibadoge** [comment]
Hello @cfluke-cb we have renounced the BURN contract.

https://etherscan.io/tx/0xfc4190a053b5a107e7181f7fe8fee6417ac17087676aeeabf1f25e66acfa8a7b

**Comment by realshibadoge** [comment]
Pinging @taycaldwell @wbnns for an update to this please 🙏

**Review by wbnns — DISMISSED** [review]
ACK

**Review by annieke — DISMISSED** [review]

**Review by annieke — DISMISSED** [review]

**Review by hamdiallam — DISMISSED** [review]

**Review by wbnns — APPROVED** [review]

**Review by annieke — DISMISSED** [review]

**Review by annieke — DISMISSED** [review]

**Review by hamdiallam — DISMISSED** [review]

**Comment by realshibadoge** [comment]
> Hi @realshibadoge
> 
> your account seems to autodismiss reviews. Please diagnose this, can't merge in this pr

It appears to be a strange GitHub bug. https://github.com/orgs/community/discussions/58535

Most solutions say re-opening this PR will fix the issue. Can we try that or should I make a new PR?

**Comment by realshibadoge** [comment]
@hamdiallam @annieke @wbnns apologies for the ping. Should I open a new PR for this or can we try to re-open this one as the comments in the discussion above suggest will work?

**Comment by wbnns** [comment]
@realshibadoge No prob! Let's open a new PR. 👍

**Pull request closed without merging**
