### PR TITLE
Add base dai deployment

### PR DESCRIPTION
**Pull request by hexonaut**
**Description**

I've deployed [a standard erc20 for dai](https://basescan.org/address/0x50c5725949a6f0c72e6c4a641f24049a917db0cb#code) on the BASE chain following [these directions](https://docs.base.org/tokens/list/) and am adding the address here. I used the factory to deploy.

**Tests**

No tests as per the instructions.

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
thanks, looking!

**Comment by roberto-bayardo** [comment]
@hexonaut do you require a goerli / base-goerli deployment as well?

**Comment by hexonaut** [comment]
We don't require it, but I suppose it makes sense to do that too.

**Comment by roberto-bayardo** [comment]
Up to you, an do it in a separate PR too if you prefer.

**Comment by hexonaut** [comment]
Separate PR works I'll do that soon.

**Comment by roberto-bayardo** [comment]
Could you submit the contract to the explorer for verification?  Usually this happens automatically with factory tokens, which I'm looking into.

**Comment by hexonaut** [comment]
> Could you submit the contract to the explorer for verification? Usually this happens automatically with factory tokens, which I'm looking into.

Where is the code? The Base instructions do not specify any of this.

**Comment by roberto-bayardo** [comment]
> > Could you submit the contract to the explorer for verification? Usually this happens automatically with factory tokens, which I'm looking into.
> 
> Where is the code? The Base instructions do not specify any of this.

Yeah good point realized this may be non-trivial, let me just ask the explorer providers why this isn't happening automatically.  Code is here: https://basescan.org/address/0x4200000000000000000000000000000000000012#code

> Also, are you with Base team or Optimism?

Base

**Comment by hexonaut** [comment]
Added a goerli deploy as well.

**Review by roberto-bayardo — APPROVED** [review]
Got the contract verified on basescan so this is good to go from the Base side

**Pull request merged**
