### PR TITLE
Add base address of ARIA20

### PR DESCRIPTION
**Pull request by gnarco**
Add ARIA20 token to Base standard bridge.

Aria20 is the native token for Arianee Protocol : https://arianee.org

https://www.coingecko.com/en/coins/arianee

@roberto-bayardo

### CODE REVIEW

**Comment by hamdiallam** [comment]
Hi @gnarco, the title states a base address is being added but don't see one listed in the files changed

any chance you haven't pushed ur latest changes?

**Comment by gnarco** [comment]
@hamdiallam It was my mistake. Fixed.

**Comment by spacesailor24** [comment]
@gnarco The validation script is failing with

```
error: ARIA20 on chain ethereum token 0xeDF6568618A00C6F0908Bf7758A16F76B6E04aF9 has incorrect name
```

The name you have in the config is `ARIA20`, but the name for the ETH contract is `ARIANEE`, and for Base it's `Arianee`. Please update the names to match and run the verification script locally to make sure it passes

**Comment by gnarco** [comment]
Before making any changes, I want to be sure : 

On Ethereum mainnet : 
Name = ARIANEE
Symbol = ARIA20

On Base : 
Name = Arianee
Symbol = ARIA20

In config 
Name = Arianee
Symbol = ARIA20


The issue is the case in the name in Base and in config ? 
If yes, do you confirm, that I need to redeploy a token on base with the right case, and update the config accordingly ? 
@spacesailor24

**Comment by gnarco** [comment]
After checking the validation process, it seems it was a case issue. 
I just deploy a new token with the right case

**Comment by hamdiallam** [comment]
> After checking the validation process, it seems it was a case issue. I just deploy a new token with the right case

Yea try to enforce matching token property fields unless it's absolutely necessary to break

**Comment by gnarco** [comment]
it seems broken again ??

**Comment by gnarco** [comment]
Hi @roberto-bayardo 

Any news ?

**Comment by roberto-bayardo** [comment]
apologies taking a look

**Review by roberto-bayardo — APPROVED** [review]
looks good for base

**Comment by gnarco** [comment]
@hamdiallam @nitaliano 
How can we finish the process ? 

Thanks !

**Review by hamdiallam — APPROVED** [review]
yep! Sorry for the delay

**Pull request merged**
