### PR TITLE
Base address for UNI

### PR DESCRIPTION
**Pull request by jbarber13**
**Description**

Add the UNI address to the token list for the Base bridge.

### CODE REVIEW

**Comment by cfluke-cb** [comment]
Hi @jbarber13 can we separate this into a PR for each token? 
For the USDT token, can this be redeployed with the newest token factory? https://docs.base.org/docs/base-contracts#base-mainnet It currently looks like a copy of the OP version from 8/21

**Review by rcbgr — COMMENTED** [review]
your json is broken

**Comment by jbarber13** [comment]
> your json is broken

@rcbgr 
Can you elaborate on what is wrong with the JSON? It passes when I run the validation 
image

**Comment by wbnns** [comment]
@jbarber13 

Heya, are you affiliated with Uniswap?

**Review by wbnns — CHANGES_REQUESTED** [review]
Pending confirmation that this is the canonical UNI.

**Comment by jbarber13** [comment]
@wbnns 
> Heya, are you affiliated with Uniswap?

Hello, 
I am with GFX Labs, we are a [delegate](https://www.tally.xyz/gov/uniswap/delegate/0xa6e8772af29b29b9202a073f8e36f447689beef6) for Uniswap.

**Comment by wbnns** [comment]
@jbarber13 

Thanks for confirming! We should hopefully have an update soon. We are also confirming via our channels with the Uniswap team that they would like this to be the canonical UNI on Base.

**Comment by wbnns** [comment]
@jbarber13 

Heya! Thanks for your patience, just wanted to follow-up! Can you link to any governance post alongside this deployment that would confirm it's approval?

**Comment by erin-koen** [comment]
Hey - gov lead from the uniswap foundation here (eek37 on the forum and on twitter). There is no gov post saying "the address of UNI on Base is 0x...". However, there is a post proposing to provide UNI-denominated liquidity incentives to L2 deployments of the protocol [here](https://gov.uniswap.org/t/uniswap-revitalization-and-growth/22616). Base is one of those L2s, and UNI incentives are currently being provided via a Merlkl distributor contract on three pools (see deets [here](https://merkl.angle.money/?times=active%2Cfuture%2C&phrase=&chains=534352%2C).

This proposal's author was Getty Hill who founded GFX. The proposal passed and GFX has helped to implement by, among other things deploying the token on various L2 chain including base ( https://basescan.org/token/0xc3de830ea07524a0761646a6a4e4be0e114a3c83#code).

Thanks

**Comment by wbnns** [comment]
@erin-koen 

Heya! Thanks for these details! We're reviewing and will follow-up asap. Appreciate all of the additional context. 🤝

**Review by wbnns — APPROVED** [review]
Thanks all!

**Review by annieke — APPROVED** [review]

**Pull request merged**
