### PR TITLE
add base-goerli cbETH

### PR DESCRIPTION
**Pull request by roberto-bayardo**
- Update cbETH config with the goerli-base contract addresses as our first case of goerli-base token listing.

**Testing:** Ran the validate script for token cbEth and confirmed the new entries do not cause new validation failures. There are existing validation failures from the cbETH Goerli contract which has a non-matching token symbol & name. Apparently this is because the contract was deployed on Goerli before they had settled on "cbETH" as the symbol to use on mainnnet.

```
$ yarn validate --datadir ./data/ --tokens cbETH                                                 0s
yarn run v1.22.19
$ ts-node ./bin/cli.ts validate --datadir ./data/ --tokens cbETH
[ 'cbETH' ]
error: cbETH on chain goerli token 0xD0bb78d0B337aA6D3A0530DD2e58560bf00851f1 has incorrect symbol
error: cbETH on chain goerli token 0xD0bb78d0B337aA6D3A0530DD2e58560bf00851f1 has incorrect name
error Command failed with exit code 1.
```

### CODE REVIEW

**Comment by zainbacchus** [comment]
Hey @roberto-bayardo  can you please make a PR to https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/src/chains.ts which includes the Base testnet config

**Comment by zainbacchus** [comment]
Hey @roberto-bayardo, thanks for the PR! We'll take a look at this before EOW. 

In the interim can you help add the Base config to these files?
•   https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/src/chains.ts
•   https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/src/schemas.ts
•   https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/src/types.ts

**Comment by roberto-bayardo** [comment]
The validation is now passing on the new section added in this PR, but failing overall because the cbETH goerli contract has a non-matching token symbol/name.

I had to update the validate.ts script a bit to get it to work ... it was expecting a 'qResult' tag in a returned json object which now seems to be coming back as 'result'.

**Comment by roberto-bayardo** [comment]
oh and I also removed the huge oneOf in the schemas.ts file as it seems to scale n^2 with new L2s and was becoming unweildy. I hope that's OK?

**Comment by roberto-bayardo** [comment]
looks like you've upstreamed related changes; PR now merged & updated!

**Comment by roberto-bayardo** [comment]
Is this ready to go now or are you still tweaking the scripts?

**Review by tremarkley — APPROVED** [review]

**Comment by tremarkley** [comment]
@roberto-bayardo the script changes have been completed, so you are good to merge this PR

**Comment by roberto-bayardo** [comment]
@tremarkley thank you, but it says someone with write access to merge. Are you able to do it?

**Pull request merged**
