### PR TITLE
Add zunUSD and zunETH to Optimism and Base

### PR DESCRIPTION
**Pull request by MioGreen**
Add zunUSD and zunETH tokens to Optimism and Base networks.
https://www.zunami.io/

zunUSD:
Token Mainnet Address: https://etherscan.io/token/0x8C0D76C9B18779665475F3E212D9Ca1Ed6A1A0e6
Token Optimism Address: https://optimistic.etherscan.io/address/0x93C3E0fa191141c957C2632752eC35C84d0C440a
Token Base Address: https://basescan.org/token/0x6ef3864876424ADE834a7C1BE8C0CF3d71208B84

zunETH:
Token Mainnet Address: https://etherscan.io/token/0xc2e660C62F72c2ad35AcE6DB78a616215E2F2222
Token Optimism Address: https://optimistic.etherscan.io/address/0x805B93d5ff318Cc054B46d6850aF12fEB55472d6
Token Base Address: https://basescan.org/token/0x40AeED4852Df0Ae3624E7027DEdDFb972Dbc8852

### CODE REVIEW

**Comment by hamdiallam** [comment]
Hi! The validation script needs to pass

```

2024-03-20T17:43:19.6774347Z error: zunUSD on chain ethereum token 0x2b95a1dcc3d405535f9ed33c219ab38e8d7e0884 has incorrect name
```

**Comment by MioGreen** [comment]
@hamdiallam thank you for the notification. fixed.

**Review by wbnns — DISMISSED** [review]
@MioGreen 

Heya, it looks like there is a difference in the resolution/size of the zunUSD and zunETH SVGs; can you please double-check and resolve?

**Comment by MioGreen** [comment]
@wbnns

Do you have any recommendations about SVG logos?

**Comment by wbnns** [comment]
@MioGreen Hello, it appears they're rendering differently when you look at the diff for the PR (one very small, the other significantly larger).

**Review by wbnns — APPROVED** [review]
ACK

@MioGreen Thanks for building on Base 🔵

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
