### PR TITLE
MANTRA token on Base

### PR DESCRIPTION
**Pull request by BigtoMantraDev**
**Description**

Add MANTRA token to token list for Base Sepolia bridge

**Additional context**

This is MANTRA token on coingecko: https://www.coingecko.com/en/coins/mantra
Add testnet for now just for testing.

### CODE REVIEW

**Comment by BigtoMantraDev** [comment]
@cfluke-cb @wbnns @taycaldwell Please help review this PR 🙏 Thanks!

**Review by wbnns — DISMISSED** [review]
@BigtoMantraDev 

Hi there! Could you please fix the errors on this PR:
```
error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 does not exist
error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 failed to get decimals
error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 failed to get symbol
error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 failed to get name
```
Looks like there is no token named OM at the address provided on Ethereum.

**Comment by BigtoMantraDev** [comment]
> @BigtoMantraDev
> 
> Hi there! Could you please fix the errors on this PR:
> 
> ```
> error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 does not exist
> error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 failed to get decimals
> error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 failed to get symbol
> error: OM on chain ethereum token 0xCbC45aaD4a64B081a51b8ebD12a16864F3c0a930 failed to get name
> ```
> 
> Looks like there is no token named OM at the address provided on Ethereum.

Fixed! Thanks for reviewing!

**Review by wbnns — APPROVED** [review]
ACK

@BigtoMantraDev Thanks for the updates and for building on Base 🔵

**Comment by BigtoMantraDev** [comment]
@wbnns We just deployed our token on Base mainnet. Because `MANTRA DAO` is rebranded to `MANTRA`, this newly deployed token overrides the name with MANTRA.  
This rebrand message is shown on Etherscan.
image

Thanks for checking this PR again🙏

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
