### PR TITLE
Add base L2 token address for MKR

### PR DESCRIPTION
**Pull request by fmorisan**
**Description**

Adds Maker (MKR) L2 token address for Base. The contract was deployed using the `OptimismMintableERC20Factory` contract at transaction [0x10c63281910a992ddb5fa5bf29bfb0369af92a35328699864da45081fdfc61f6](https://basescan.org/tx/0x10c63281910a992ddb5fa5bf29bfb0369af92a35328699864da45081fdfc61f6).

The token's remote address has been set to [0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2](https://etherscan.io/token/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2), which is MKR's address on ETH Mainnet.

### CODE REVIEW

**Comment by fmorisan** [comment]
Tagging @cfluke-cb and @wbnns as per [this link](https://static.optimism.io/#specifying-chains)

**Comment by rcbgr** [comment]
hey @fmorisan, your JSON is invalid

**Comment by fmorisan** [comment]
looks valid to me... what's wrong with it?
image

**Review by wbnns — CHANGES_REQUESTED** [review]
@fmorisan 

Thanks for the PR! Could you please confirm your affiliation with MKR?

**Comment by fmorisan** [comment]
I confirm my affiliation to MakerDAO.

**Comment by wbnns** [comment]
@fmorisan 

Thanks for confirming. We also just wanted to confirm as a second factor through our channels. Will follow-up here as soon as I have an update!

**Review by wbnns — APPROVED** [review]
Confirmed, ACK

@fmorisan Thanks for building on Base 🔵

**Comment by fmorisan** [comment]
Thanks!

**Review by annieke — APPROVED** [review]

**Pull request merged**
