### PR TITLE
Add cbETH

### PR DESCRIPTION
**Pull request by KNWR**
**Description**
Adding [cbETH](https://etherscan.io/token/0xbe9895146f7af43049ca1c1ae358b0541ea49704) to Optimism for bridging

**Tests**
n/a

**Invariants**
n/a

**Additional context**
n/a

### CODE REVIEW

**Comment by KNWR** [comment]
Hi team, can we merge this PR as is and update the missing or "to add" fields later, as well as the Optimism Mainnet Address? We want to test that we've done this correctly for bridging on Ethereum Goerli <-> Optimism Goerli before deploying to Optimism Mainnet and making bridging available there.

**Comment by zainbacchus** [comment]
Hey there! Thanks for this PR - I do not see a contract deployed to either provided testnet address.

**Comment by roninjin10** [comment]
@KNWR I think you forgot to commit the testnet addresses

**Comment by KNWR** [comment]
Oops - sorry about that, @zainbacchus @roninjin10 - I just updated it. Appreciate the catch there.

**Comment by roninjin10** [comment]
Looks good.  Could you verify the contracts on etherscan @KNWR ?

**Comment by roninjin10** [comment]
@KNWR just noticed we accidentally named the file data,json instead of data.json.  We need to fix that for the validation to run

**Comment by KNWR** [comment]
Sorry friends, just fixed it

**Comment by roninjin10** [comment]
tyty @KNWR

**Comment by KNWR** [comment]
Hi team, this PR was merged but I don’t see it on https://app.optimism.io/bridge/deposit as an option - are there any other steps I need to follow?

**Comment by roninjin10** [comment]
@KNWR it won't show up til we update the npm package on the bridge and redeploy.  We redeploy on tuesdays wednesdays and thursdays

**Comment by yfl92** [comment]
> We redeploy on tuesdays wednesdays and thursdays

Hi friends, did we redeploy? Still don't see on https://app.optimism.io/bridge/deposit so getting a little bit worried 😢

**Pull request merged**
