### PR TITLE
add CRYO to Base and Optimism

### PR DESCRIPTION
**Pull request by schmackofant**
Add CRYO token to Optimism and Base.

This token is mainnet native.

Adding @roberto-bayardo for Base approval.

### CODE REVIEW

**Comment by roninjin10** [comment]
This pr is failing validation

```
[ 'CRYO' ]
warning: CRYO on chain ethereum token 0xf4308b0263723b121056938c2172868E408079D0 not found on CoinGecko token list
 ELIFECYCLE  Command failed with exit code 1.
error: CRYO on chain ethereum token 0xf4308b0263723b[12](https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/7970957127/job/21778828523?pr=652#step:10:13)1056938c2172868E408079D0 has incorrect name
error: CRYO on chain optimism token 0x0[14](https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/7970957127/job/21778828523?pr=652#step:10:15)02d1Bc10Ae6E96C0E494A5860748517a3c070 has incorrect name
error: CRYO on chain base token 0x1f4446fAAAed23090f324f051C3F8c5ce5aD1c36 has incorrect name
```

**Comment by schmackofant** [comment]
@roninjin10 We fixed this now, the token address is visible on Coingecko and I think now the tests should pass? Can you re-run them?

**Comment by cfluke-cb** [comment]
There is still an issue.
error: CRYO on chain ethereum token 0xf4308b0263723b121056938c2172868E408079D0 has incorrect name. Got CryoDAO
error: CRYO on chain optimism token 0x01402d1Bc10Ae6E96C0E494A5860748517a3c070 has incorrect name. Got CryoDAO
error: CRYO on chain base token 0x1f4446fAAAed23090f324f051C3F8c5ce5aD1c36 has incorrect name. Got CryoDAO

Please update the name in the PR to CryoDAO without the Token portion

**Comment by schmackofant** [comment]
> There is still an issue. error: CRYO on chain ethereum token 0xf4308b0263723b121056938c2172868E408079D0 has incorrect name. Got CryoDAO error: CRYO on chain optimism token 0x01402d1Bc10Ae6E96C0E494A5860748517a3c070 has incorrect name. Got CryoDAO error: CRYO on chain base token 0x1f4446fAAAed23090f324f051C3F8c5ce5aD1c36 has incorrect name. Got CryoDAO
> 
> Please update the name in the PR to CryoDAO without the Token portion

Thanks! Fixed that now

**Review by cfluke-cb — APPROVED** [review]
Looks good on Base side.

**Review by annieke — APPROVED** [review]

**Pull request merged**
