### PR TITLE
Add LQTY token

### PR DESCRIPTION
**Pull request by RickGriff**
Add LQTY to the token list.

### CODE REVIEW

**Review by roninjin10 — APPROVED** [review]

**Comment by roninjin10** [comment]
We usually don't add tokens that aren't on either optimism or optimism goerli

**Comment by zainbacchus** [comment]
Hi @RickGriff please update the PR to include the Optimism, Optimism Goerli, or Base Goerli address

**Comment by TokenBrice** [comment]
> Hi @RickGriff please update the PR to include the Optimism, Optimism Goerli, or Base Goerli address

Hello @zainbacchus - we would love to, but it doesn't seem possible, as the token doesn't exist on Optimism yet (it needs to be bridged first).

To clarify the situation:
- LQTY is a token minted on mainnet and powered by an **immutable** contract
- It's [bridged to Arbitrum](https://arbiscan.io/address/0xfb9e5d956d889d91a82737b9bfcdac1dce3e1449).
=> Why not do the same on Optimism?

**Comment by tremarkley** [comment]
@TokenBrice here is a tutorial you can follow for deploying the L2 token on Optimism: https://github.com/ethereum-optimism/optimism-tutorial/tree/01e4f94fa2671cfed0c6c82257345f77b3b858ef/standard-bridge-standard-token

**Pull request closed without merging**
