### PR TITLE
Add ❤️ to base

### PR DESCRIPTION
**Pull request by ENSpunks**
@roberto-bayardo 

Add ❤️ to base

I did my best to follow the documentation at https://docs.base.org/tokens/list/  but its possible I did not do the deploy correctly using  OptimismMintableERC20Factory (my first time deploying to base or any L2).   

This is the tx if I need to do something over: https://basescan.org/tx/0x77645524ac7df79d4da505404c0a4dad5d834feee5eb3be57e5e0245249249c8#eventlog

### CODE REVIEW

**Review by cfluke-cb — APPROVED** [review]
Looks good from Base side.

**Comment by ENSpunks** [comment]
@spacesailor24 pinging you, I think this PR is cleared by base and ready for you to approve.

**Review by cfluke-cb — APPROVED** [review]
Looks good from Base side.

**Comment by roninjin10** [comment]
We are gonna change this folder name to `heart` since a :heart: as a file name is not ideal

**Comment by ENSpunks** [comment]
Hi,In addition to the folder name change from ❤️ to “LIKE” the token symbol was changed in the json on mainnet and base resulting in a conflict between the repo and onchain data.The symbol should be reverted back to “❤️” in the json consistent with the chain and the update only to the repo folder name. On Mar 13, 2024, at 4:35 PM, Will Cory ***@***.***> wrote:﻿
We are gonna change this folder name to heart since a ❤️ as a file name is not ideal

**Pull request merged**
