### PR TITLE
Modified TKN to add bridged Base token address

### PR DESCRIPTION
**Pull request by technicallykind**
**Description**

Adding the TKN Base token address to join the existing ETH Mainnet and OP Mainnet addresses

### CODE REVIEW

**Comment by technicallykind** [comment]
@roberto-bayardo, thank you for your consideration! TKN is already actively traded and included in the official Optimism bridge. Additionally we are a whitelisted Aerodrome token and are looking to bridge to the Base network there.

**Comment by rcbgr** [comment]
LGTM

**Comment by technicallykind** [comment]
> LGTM

Thanks @rcbgr !

We're going live on Aerodrome today and getting this merged would be really helpful for users who are asking to bridge from OP Mainnet to Base. Thanks everyone! @roberto-bayardo

**Review by roberto-bayardo — APPROVED** [review]

**Comment by roberto-bayardo** [comment]
@hamdiallam this is good to go from Base side.

**Comment by technicallykind** [comment]
@jakim929 Would you mind taking a look? Thanks!

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
