### PR TITLE
feat: added bepro token

### PR DESCRIPTION
**Pull request by ickas**
**Description**

Added $BEPRO token. [Bepro](https://bepro.network/) is a task-based marketplace created to help organizations and builders thrive. Organizations can easily create and launch tasks, while builders have the opportunity to work on them and earn crypto as payment, providing a more efficient and transparent collaboration.

Ethereum:
https://etherscan.io/address/0xcf3c8be2e2c42331da80ef210e9b1b307c03d36a

Base:
https://basescan.org/address/0xf1095aa7DC127ed45441aCfb742694d6a0261b00

### CODE REVIEW

**Comment by ickas** [comment]
cc @hvasconcelos

**Comment by cfluke-cb** [comment]
Hi @ickas The name of the token on L1 vs L2 is different. L1 is BetProtocolToken and L2 is BEPRO Token. Can these match?

**Comment by ickas** [comment]
> Hi @ickas The name of the token on L1 vs L2 is different. L1 is BetProtocolToken and L2 is BEPRO Token. Can these match?

*BetProtocolToken* was the initial name of the protocol, but in the meantime, we renamed it, and we prefer to use the *Bepro* name.

**Comment by cfluke-cb** [comment]
Can you add a name override for ethereum token name? example in readme https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#per-token-overrides

**Review by wbnns — DISMISSED** [review]
@ickas 

Heya! Thanks for the changes! Looks like an override still needs to be added for Base:
```
error: BEPRO on chain base token 0xf1095aa7DC127ed45441aCfb742694d6a0261b00 has incorrect name. Got BEPRO Token
```

**Review by wbnns — APPROVED** [review]
@ickas 

Thanks for the updates and for building on Base 🔵

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
