### PR TITLE
Added IMGNAI

### PR DESCRIPTION
**Pull request by RustlerK**
- NB: Token contract contains the ability to apply per-pool fee on v2 pool transactions, and has the bridge contract excluded/restricted from being added as a taxable address.

All transfers to/from any excluded addresses (pre-filled with 0x4200000000000000000000000000000000000010) cannot be charged any fee on tx.

base contract deployment will be held by the imgnai.eth multisig, ensuring against any erroneous fee pair additions.

**Description**

Added imgnAI Base contract & details

**Tests**

Test contract deployed on BASE, ensured no interference with fee on uniswap v2 pool txs against any bridge addr. Carried out additional mint/burn testing from deployer wallet, with deployer set as BRIDGE.

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@RustlerK 

Hi there! The CI / verification of the data submitted is failing on this PR. Could you please fix?

**Comment by RustlerK** [comment]
Hi @wbnns - redeployed base contract to align with imgnai's original name/symbol, and updated in the data json.

Looks like all automated tests are now passing as expected - could you re-review when ready?

**Review by wbnns — CHANGES_REQUESTED** [review]
@RustlerK 

Thanks! Can you please add the `"nonstandard": true,` option to your `data.json` as well?

**Comment by RustlerK** [comment]
Hey @wbnns - apologies for the delay, updated as requested. Please let me know if anything else is needed here :)

**Review by wbnns — APPROVED** [review]
ACK

@RustlerK Thanks for building on Base and also for the updates 🔵

**Review by wbnns — DISMISSED** [review]
@RustlerK 

Heya, we noticed that the validation is still failing; it looks like it's because the name and symbol don't perfectly match L1. Can you please update or use overrides?

Details here:
https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#automated-checks

**Comment by RustlerK** [comment]
Hey @wbnns - problem in validation seems to be stemming from the actual token name;

```
These errors caused the validation to fail:
final token list is invalid: [
  {
    "instancePath": "/tokens/191/name",
    "schemaPath": "#/properties/name/pattern",
    "keyword": "pattern",
    "params": {
      "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$"
    },
    "message": "must match pattern \"^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$\"",
    "schema": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
    "parentSchema": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
      "examples": [
        "USD Coin"
      ]
    },
    "data": "Image Generation AI | imgnAI.com"
  }
]
```

This is our actual/valid token name on Ethereum; https://etherscan.io/token/0xa735a3af76cc30791c61c10d585833829d36cbe0

However, we have since rebranded to Imagine AI; I've re-deployed our token contract on Base to reflect this, and updated it in the data.json.

For the Ethereum override, I've used "Image Generation AI" (cutting the | url suffix) - looks like all tests are passing now :)

**Review by wbnns — APPROVED** [review]
ACK

@RustlerK Thanks for fixing 🤝

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
