### PR TITLE
Add Unlock Discount Token to the Superchain Token List

### PR DESCRIPTION
**Pull request by clemsos**
**Description**

Adds UDT to the Superchain Token List

**Tests**

Followed the [process in README](https://github.com/ethereum-optimism/ethereum-optimism.github.io#review-process-and-merge-criteria)

### CODE REVIEW

**Comment by cfluke-cb** [comment]
Hi @clemsos can you update the name and symbol values to match the contract?
error: UDT on chain optimism token 0x35CCe76D854c6E90F665C2B49899E158da9D517E has incorrect symbol
error: UDT on chain optimism token 0x35CCe76D854c6E90F665C2B49899E158da9D517E has incorrect name. Got UnlockDiscountToken (bridged)
error: UDT on chain base token 0xE68858e8fe7b491B13d1aefccBBC7367D1f1848e has incorrect symbol
error: UDT on chain base token 0xE68858e8fe7b491B13d1aefccBBC7367D1f1848e has incorrect name. Got UnlockDiscountToken (bridged)
error: UDT on chain base-sepolia token 0x345F99F6873866f8b73aD4a500396c4635E0E755 has incorrect name. Got UnlockDiscountToken

**Comment by julien51** [comment]
Thanks @cfluke-cb ! Clement is OOO for a few days, so I redeployed the contracts!
Since we used the [tutorial there](https://docs.optimism.io/builders/app-developers/tutorials/standard-bridge-standard-token) and you require names/symbol to match, I think it could be a great idea to just have that script retrieve the name/symbol from the L1.

Let us know if you want us to contribute that, we'd be happy to!

**Comment by julien51** [comment]
Please let us know if there is anything we need to do @annieke and @cfluke-cb ?

**Comment by julien51** [comment]
Any help here would be greatly appreciated! Thanks!

**Review by wbnns — APPROVED** [review]
ACK

@clemsos @julien51 Thank you all for your patience, apologies for the delayed reply. 🙏

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
