### PR TITLE
Add FreeTrump (TRUMP) token data and logo

### PR DESCRIPTION
**Pull request by RealFreeTrump**
**Description**

This pull request adds support for the FREETRUMP (TRUMP) token to the Base chain. The changes include the addition of a 256x256 SVG logo and a data.json file containing the token's metadata. FREETRUMP ERC is an ERC20 political meme coin dedicated to protecting the freedom of President Donald J. Trump.

**Tests**

No specific tests have been added for this pull request as it primarily involves adding static data and assets. The automated checks provided by the repository will ensure that the changes conform to the required standards and guidelines.

**Additional context**

This addition allows the FREETRUMP token to be listed on the Base chain, enabling low-fee swapping for users. The token details provided in the data.json file include its name, symbol, decimals, description, website, X account, and contract address on the Ethereum network.

**Metadata**

This pull request does not fix any specific issue but adds new functionality to support the FREETRUMP token.

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@RealFreeTrump 

Hello, this PR is failing CI/CD with validation errors. Can you please fix?

**Comment by RealFreeTrump** [comment]
Have submitted a pull request to fix it. Maybe we submitted in the wrong place?

**Comment by RealFreeTrump** [comment]
image

**Comment by RealFreeTrump** [comment]
@wbnns please check. thank you!

**Comment by RealFreeTrump** [comment]
The symbol in the contract is indeed TRUMP. Maybe something is wrong in the
code I submitted

**Review by wbnns — CHANGES_REQUESTED** [review]
@RealFreeTrump 

It looks like you are also missing a destination chain address. This repository is for bridging tokens between L1 and to L2 networks on the Superchain. Can you please update?

**Comment by wbnns** [comment]
@RealFreeTrump 

Since it's been some time and we still haven't heard back, closing this PR for now. If you'd still like to pursue this change, please let us know and we can reopen.

**Pull request closed without merging**
