### PR TITLE
Update POPO (logo.svg)

### PR DESCRIPTION
**Pull request by Protojae**
This pull request updates the logo.svg file with a new and improved design. The previous logo has been replaced to better reflect the current branding and aesthetic of the project. This change enhances the visual appeal and aligns with our updated design standards.

### CODE REVIEW

**Review by wbnns — APPROVED** [review]
@Protojae Updated, thanks!

**Review by wbnns — CHANGES_REQUESTED** [review]
@Protojae 

Looks like CI/CD has failed on this with the following issue:
```
error: POPO on chain base token 0x7422f030958Edf9884cE9c46a211029E03eF6da7 has incorrect name. Got Pepe’s Dog
```
Can you please update to the metadata? Looks like the issue is that onchain it has a smart apostrophe and in the token metadata here in the repo it is a standard apostrophe.

(’ vs ')

**Comment by Protojae** [comment]
Okay yeah for sure thank you, I did not realize the difference there! I'll get that fixed!

**Comment by Protojae** [comment]
I think everything should be in order now! Thanks again, learning new things every day! Who knew there was a difference xD

**Comment by Protojae** [comment]
I'm sorry I didn't know making changed to the directory in my branch would be pushing through to here, I was preparing to push through a separate project. I am new to github, I hope I didn't mess anything up :s 
Chiggles and Popo are two separate projects, both ran by me. Chiggles I created, popo is a CTO.

**Comment by wbnns** [comment]
@Protojae 

Thanks for the updates! Can you please open a separate PR for Chiggles and undo the change in this repo? We prefer to have one PR per token so we can organize reviews.

**Comment by wbnns** [comment]
@Protojae 

Since it's been some time and we haven't heard back, closing this PR for now. If you're still interested in pursuing these changes, please let us know and we can reopen. 👍

**Pull request closed without merging**
