### PR TITLE
Add usdc erc20 on Mode

### PR DESCRIPTION
**Pull request by ssallam**
**Description**

Add usdc erc20 on Mode

### CODE REVIEW

**Comment by hamdiallam** [comment]
Hey @ssallam,

Sorry this was closed. Befor re-opening, can you provide usdc documentation that this is the official contract address to be used on the Mode network? Checking https://www.circle.com/en/usdc/developers, Mode isn't listed as a native deployment

**Comment by agileurbanite** [comment]
This isn't the native USDC but a wrapped USDC as an erc20 btw.

**Comment by agileurbanite** [comment]
@hamdiallam this is the contract address `0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48` https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

Some info about Mode:
https://twitter.com/Optimism/status/1749872693451817188

**Comment by ssallam** [comment]
> Hey @ssallam,
> 
> Sorry this was closed. Befor re-opening, can you provide usdc documentation that this is the official contract address to be used on the Mode network? Checking https://www.circle.com/en/usdc/developers, Mode isn't listed as a native deployment

Thanks @hamdiallam 
I added more information in the top comment, please let me know if you required more info

As mentioned by @agileurbanite above, this USDC token is on the standard bridge and is not the native USDC.

**Comment by ssallam** [comment]
https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/599

**Pull request closed without merging**
