### PR TITLE
Add USC token

### PR DESCRIPTION
**Pull request by dusan-mrsic**
Add USC token:

Ethereum:
https://etherscan.io/address/0x38547d918b9645f2d94336b6b61aeb08053e142c

Base:
https://basescan.org/address/0x38547d918b9645f2d94336b6b61aeb08053e142c

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@dusan-mrsic 

Hi there! After the twitter entry, can you please add the "nonstandard": true, option?

**Comment by dusan-mrsic** [comment]
@wbnns Hey, added requested change

**Comment by dusan-mrsic** [comment]
@wbnns Also I have one more question, I don't know whom I can ask about that, maybe you can help. I want to add one more token 'CHI' but there is already token some 'CHI' token. What should be name for folder then, cause our symbol is also "CHI" ? Thanks in advance!

**Comment by wbnns** [comment]
> @wbnns Also I have one more question, I don't know whom I can ask about that, maybe you can help. I want to add one more token 'CHI' but there is already token some 'CHI' token. What should be name for folder then, cause our symbol is also "CHI" ? Thanks in advance!

Heya, good question, I'm looking into this for you and will follow-up as soon as I have an answer. 👍

**Review by wbnns — APPROVED** [review]
@dusan-mrsic 

Thanks for the updates and also for building on Base 🔵

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
