### PR TITLE
add ACX token

### PR DESCRIPTION
**Pull request by nicholaspai**
**Description**

Adding Across bridge token (ACX).

**Additional context**

L2 counterpart was created via the L2 standard token factory [here](https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000012)

### CODE REVIEW

**Review by nickbalestra — APPROVED** [review]

**Comment by nickbalestra** [comment]
Hey @nicholaspai thanks for this PR, I see you marked it as draft, let us know when ready so that we can merge it!

**Comment by nicholaspai** [comment]
> Hey @nicholaspai thanks for this PR, I see you marked it as draft, let us know when ready so that we can merge it!

Will do! I'm just confirming with the team that this is the address we want to actually use 😅, sorry to waste your time

**Comment by nickbalestra** [comment]
Oh nothing to be sorry :) Just wanted to make sure we can move fast if you needed. Thanks a lot for the PR and just let us know when you want us to ship it. No rush/pressure :)

**Comment by nicholaspai** [comment]
> Oh no worries @nicholaspai! I just wanted to make sure we can move fast if you needed. Thanks a lot for the PR and just let us know when you want us to ship it. No rush/pressure :)

Awesome, done! PTAL when you have a chance :)

**Comment by nickbalestra** [comment]
Done, thank you so much!

**Pull request merged**
