### PR TITLE
adding PolySwarm

### PR DESCRIPTION
**Pull request by scsich**
**Description**
Added PolySwarm (NCT) token to data folder

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@scsich 

Hello, thanks for the PR! Could you please ensure the logo file conforms to the required format?

https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#add-a-logo-to-your-folder

**Comment by scsich** [comment]
@wbnns thanks for this. Adjusting to 256x256 (assuming that is max, unclear in https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#add-a-logo-to-your-folder). Let me know if further changes needed.

**Comment by wbnns** [comment]
@scsich 

Thanks for the update! Apologies if it wasn't clear in the README, the logo actually needs to be named `logo.svg`. This needs to be updated on this PR since the name is `polyswarm.svg`. Hope that helps clarify!

**Comment by scsich** [comment]
@wbnns thanks for the clarification, makes sense now. Appreciate the follow up.

**Comment by scsich** [comment]
Hi @wbnns checking if this is all good now?

**Review by wbnns — APPROVED** [review]
ACK

@scsich Thanks for the updates and for building on Base! 🔵

**Pull request merged**
