### PR TITLE
Adding Apu Token to Base

### PR DESCRIPTION
**Pull request by adrbull**
This github is to add APU from ETH network to Base
@cfluke-cb 

Apu, also known as Peepo or Helper, is a pepe-variant that is used to represent a much younger, kinder and more naive anthropomorphic frog.

Fed up with low-effort memecoins, more often than not led by deceptive developers, Apu decided to create his own fairly launched, fully transparent coin: $APU – the one and only coin for all frens.

Having already conquered the internet and the hearts of millions of people, Apu is now on his way to conquer the cryptosphere. If you consider yourself a fren, feel free to join us on this amazing ride to the only place where a character like Apu belongs to: the moon.

Website: https://apu.community/
Contract Address ETH L1: 0x594daad7d77592a2b97b725a7ad59d7e188b5bfa

***

A Story of Resilience and Community Triumph
The Apu coin narrative is one marked by an extraordinary journey of resilience, unity, and rebirth. Born from the vibrant enthusiasm of the cryptocurrency community, $Apu's trajectory took an unexpected turn when the original developer, executed a rug pull—a move that threatened the very existence of the coin and shook the community to its core.

However, the story did not end there. In the aftermath of the rug pull, the $Apu community, refusing to be defeated, rallied together in an inspiring display of solidarity and determination to take over the reins of the project.

This pivotal moment marked the beginning of a new era for $Apu. Through collective effort and unwavering faith in the project, the community not only revived the coin but also set it on a path toward new opportunities and growth.

The community's takeover of $Apu is a testament to the transformative power of unity and shared vision, showcasing how, even in the face of adversity, a dedicated community can steer a project towards success and innovation. Today, $Apu stands as a symbol of community empowerment, a beacon of hope for projects facing similar challenges. It is a reminder that in the dynamic world of cryptocurrency, the spirit of collaboration and resilience can turn setbacks into stepping stones for a brighter future.

—More of this story will be unveiled in the upcoming "Book of $Apu." Stay tuned, frens!

"The greatest comeback in crypto history."

***

**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by annieke** [comment]
fyi svg is not rendering

**Comment by adrbull** [comment]
> fyi svg is not rendering

Logo has been reupload

**Comment by adrbull** [comment]
> fyi svg is not rendering

Also updating the comment. It might give a better information of who we are.

**Review by cfluke-cb — CHANGES_REQUESTED** [review]
Can you remove the second logo image? Logo APU.svg

**Review by adrbull — COMMENTED** [review]
File apu logo.svg is removed as requested by @cfluke-cb

**Review by wbnns — APPROVED** [review]
ACK

**Review by annieke — APPROVED** [review]

**Pull request merged**
