### PR TITLE
tscTokenPullRequest

### PR DESCRIPTION
**Pull request by kuldeepak**
**Description**

A clear and concise description of the features you're adding in this pull request.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by cfluke-cb** [comment]
Hi @kuldeepak Can you upload a valid png or svg logo image?

**Comment by kuldeepak** [comment]
Hello @cfluke-cb 

I have uploaded the valid PNG logo image. Please have a look.

**Review by wbnns — CHANGES_REQUESTED** [review]
@kuldeepak 

The PNG looks good, thanks. Could you please remove the invalid SVG from the PR?

**Comment by kuldeepak** [comment]
Hello @wbnns 

Deleted data/TSC/logo.svg file.

**Review by wbnns — APPROVED** [review]
ACK

**Review by wbnns — APPROVED** [review]

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
