### PR TITLE
Add SEXY Token to Base

### PR DESCRIPTION
**Pull request by j-eth-id**
Add SEXY Token to Base Network.
[https://www.coingecko.com/en/coins/settled-ethxy-token](https://www.coingecko.com/en/coins/settled-ethxy-token)
[https://coinmarketcap.com/currencies/ethxy](https://coinmarketcap.com/currencies/ethxy)

Token Mainnet Address: [https://etherscan.io/token/0xc52fafdc900cb92ae01e6e4f8979af7f436e2eb2](https://etherscan.io/token/0xc52fafdc900cb92ae01e6e4f8979af7f436e2eb2)
Token Base Address: [https://basescan.org/token/0xd1917629b3e6a72e6772aab5dbe58eb7fa3c2f33](https://basescan.org/token/0xd1917629b3e6a72e6772aab5dbe58eb7fa3c2f33)

@roberto-bayardo for Base approval.  Thank you!

### CODE REVIEW

**Comment by hamdiallam** [comment]
Hi, the validation scripts are failing:
```

2024-03-19T15:14:00.6681197Z  ELIFECYCLE  Command failed with exit code 1.
2024-03-19T15:14:00.6689383Z error: SEXY on chain base token 0x395Ae52bB17aef68C2888d941736A71dC6d4e125 has incorrect symbol
2024-03-19T15:14:00.6691315Z error: SEXY on chain base token 0x395Ae52bB17aef68C2888d941736A71dC6d4e125 has incorrect name
```

**Comment by j-eth-id** [comment]
@hamdiallam Updated the diff! The validation should now pass

**Comment by cfluke-cb** [comment]
Hi @hamdiallam Is the token intended to have an uncapped supply? 
Do you want the token to be sent to 0x address and also have a burn function?

**Comment by j-eth-id** [comment]
@cfluke-cb Yes, the token is intended to have an uncapped supply.  The Base token at https://basescan.org/token/0xd1917629b3e6a72e6772aab5dbe58eb7fa3c2f33 is configured as intended

**Review by cfluke-cb — APPROVED** [review]
Looks good from Base side.

**Review by annieke — APPROVED** [review]

**Pull request merged**
