### PR TITLE
added kiddo token

### PR DESCRIPTION
**Pull request by divyesh-puri**
**Description**
Added kiddo token to standard bridge

### CODE REVIEW

**Comment by divyesh-puri** [comment]
@Nicca42 Created this which resolves the issue mentioned in #79 and created a new one as that made things a bit messy.

**Comment by divyesh-puri** [comment]
lmao closed this accidentally, nvm about that.

**Comment by smartcontracts** [comment]
Hi! We recently updated our token list to a new v2 system that simplifies the process of adding new tokens and will ultimately speed up the review process. Please refer to our [new README](https://github.com/ethereum-optimism/ethereum-optimism.github.io#adding-a-token-to-the-list) for information about the new process. You may have to close this PR and open a new one instead. Apologies for the inconvenience.

**Comment by smartcontracts** [comment]
Hi! We recently updated our token list to a new v2 system that simplifies the process of adding new tokens and will ultimately speed up the review process. Please refer to our [new README](https://github.com/ethereum-optimism/ethereum-optimism.github.io#adding-a-token-to-the-list) for information about the new process.

Our new token listing process is significantly simplified and makes the steps to add a new token much easier. Since this PR is using the old token listing format, we are closing this PR and would like to ask you to open a new PR with the updated format. Our apologies for the inconvenience here, we're doing our best with the new process to make sure that future token listing PRs get feedback quickly.

**Pull request closed without merging**
