### PR TITLE
Add config for wstETH token on Sepolia and Optimism-Sepolia

### PR DESCRIPTION
**Pull request by kovalgek**
**Description**

Add Sepoliaa and Optimism-Sepolia testnet configs for wstETH token.

**Tests**

According to the instruction, tests are not required.

### CODE REVIEW

**Comment by spacesailor24** [comment]
Needs to be verified on [OP Sepolia Blockscout](https://optimism-sepolia.blockscout.com/address/0x24B47cd3A74f1799b32B2de11073764Cb1bb318B?tab=contract) (I'm attempting to verify it)

**Comment by spacesailor24** [comment]
Contract is not verified on [OP Sepolia](https://optimism-sepolia.blockscout.com/address/0x24B47cd3A74f1799b32B2de11073764Cb1bb318B?tab=contract). The deploy bytecode varies significantly

image

**Comment by spacesailor24** [comment]
@kovalgek Can you verify the contract on OP Sepolia?

**Comment by kovalgek** [comment]
> Contract is not verified on [OP Sepolia](https://optimism-sepolia.blockscout.com/address/0x24B47cd3A74f1799b32B2de11073764Cb1bb318B?tab=contract). The deploy bytecode varies significantly
> 
> Left is from ETH Sepolia, right OP Sepolia
> 
> image

@spacesailor24 I think you compared two different contracts. wstETH on Sepolia and wstETH on Optimism Sepolia are different contracts.

- wstETH sourcecode on Sepolia https://github.com/lidofinance/lido-dao/blob/master/contracts/0.6.12/WstETH.sol
- wstETH sourcecode on Optimism Sepolia https://github.com/lidofinance/lido-l2/blob/main/contracts/token/ERC20Bridged.sol

Both contracts are verified on etherscan btw:
**sepolia**
https://sepolia.etherscan.io/address/0xB82381A3fBD3FaFA77B3a7bE693342618240067b#code

**sepolia-optimism**
https://sepolia-optimism.etherscan.io/address/0x24B47cd3A74f1799b32B2de11073764Cb1bb318B#code
https://sepolia-optimism.etherscan.io/address/0xaB0c6F1015b644c252064155759Cdc90a6CBd50d#code

**Review by roninjin10 — APPROVED** [review]

**Pull request merged**
