### PR TITLE
wHOGE data

### PR DESCRIPTION
**Pull request by hoge-rileous**
I think this should work. The "." in the symbol name of our previous attempt caused problems on Basescan.
So we deployed a new wrapper and got the Base token aligned.
Thanks

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@hoge-rileous 

Hi there! Can you please verify the source code for the contract on Ethereum?

**Comment by hoge-rileous** [comment]
Hi,
Etherscan didn't register it for some reason but there's verified source on Sourcify:
https://repo.sourcify.dev/contracts/full_match/1/0x7c8E7A5CA7c6EdCEc00B6bF12DA207AEe4Af5513/
I will take another pass at Etherscan but maybe this is enough

**Comment by hoge-rileous** [comment]
Etherscan source is registered now too @wbnns , cheers

**Review by wbnns — APPROVED** [review]
ACK

@hoge-rileous Thanks for the updates and for building on Base 🔵

**Review by annieke — APPROVED** [review]

**Pull request merged**
