### PR TITLE
Adds THX Token

### PR DESCRIPTION
**Pull request by peterpolman**
Add THX Token

Ethereum:
https://etherscan.io/token/0xe632ea2ef2cfd8fc4a2731c76f99078aef6a4b31

Base:
https://basescan.org/token/0xb363c1235734f4C036Eb82C84C87e099C316fb48

### CODE REVIEW

**Review by wbnns — APPROVED** [review]
ACK

@peterpolman Thanks for building on Base 🔵

**Comment by peterpolman** [comment]
> ACK
> 
> @peterpolman Thanks for building on Base 🔵

Hi @wbnns! Thanks for the approval. I've noticed mergify is not able to merge. 
- Is there an action needed from my end to resolve this? 
- Additionally, when would users be able to bridge this token through superbridge UI?

**Review by nickbalestra — DISMISSED** [review]

**Comment by nickbalestra** [comment]
@Mergifyio rebase

**Comment by nickbalestra** [comment]
@peterpolman can I ask you to try rebase your PR, trying to debug what is causing issues with mergify - Thanks!

**Comment by peterpolman** [comment]
@nickbalestra Consider it done! Since these changes were approved could you please manually merge this in first? Our marketing teams are currently blocked by this one🙏

As far as I can see mergify seems to lack permissions, I've read the [suggested solution](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) but can't find the required config in my fork...

Shall I open another PR for you so we can continue debugging this issue there after you merge this in manually?

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
