### PR TITLE
adding opn token - the migrated token of get protocol nft ticketing

### PR DESCRIPTION
**Pull request by kasper-keunen**
Added OPN token details for the base l2. This is the token that will be the migrated token of GET Protocol. 
Ethereum address OPN: https://etherscan.io/address/0xc28eb2250d1AE32c7E74CFb6d6b86afC9BEb6509
Website: https://onopen.xyz/
Website pre migration: https://www.get-protocol.io/

### CODE REVIEW

**Comment by kasper-keunen** [comment]
Hi there - was wondering if there was an update on this the migration is tomorrow and we are planning on launching on base but without a bridge mapping this will be problematic.

**Comment by kasper-keunen** [comment]
Hey @cfluke-cb would be great if you could help us get this merged - the migration of GET to OPN is tomorrow and we need the bridge :)  - thanks!

**Comment by kasper-keunen** [comment]
@cfluke-cb is there an update on this PR? Would appreciate an update so we know how to proceed here - we can explore other bridging options as wormhole but we absolutely prefer the more 'native' approach! Thanks for the help - hope we can get some clarify.

**Comment by kasper-keunen** [comment]
Any update @cfluke-cb ?

**Review by rcbgr — APPROVED** [review]

**Comment by kasper-keunen** [comment]
Hey @rcbgr it seemed that the decimals where a string - i fixed that now! Hope it is good right this!

**Review by wbnns — APPROVED** [review]

**Comment by wbnns** [comment]
@kasper-keunen 

Hi there! Please accept my sincerest apologies; I'm sorry that you haven't received an update on this PR before today and thanks so much for your patience.

Also approving this for merge.

**Comment by kasper-keunen** [comment]
> @kasper-keunen
> 
> Hi there! Please accept my sincerest apologies; I'm sorry that you haven't received an update on this PR before today and thanks so much for your patience.
> 
> Also approving this for merge.

Perfect! Thanks a lot! Have a good weekend.

**Review by annieke — APPROVED** [review]

**Comment by wbnns** [comment]
@annieke @hamdiallam 

ACK

**Pull request merged**
