### PR TITLE
Add SHIBDOGE to Base Chain

### PR DESCRIPTION
**Pull request by realshibadoge**
Add ShibaDoge Token on Base

ShibaDoge: https://shibadoge.com/
Ethereum: 0x6ADb2E268de2aA1aBF6578E4a8119b960E02928F
Base: 0x606B2Db8Bf642677Fe12E8F067bF55145A350cb5

### CODE REVIEW

**Comment by hamdiallam** [comment]
Hey @realshibadoge, validation scripts are failling

```
2024-03-28T18:32:23.9989382Z error: BURN: instance.decimals: is not of a type(s) integer
2024-03-28T18:32:23.9990660Z error: ShibDoge: instance.decimals: is not of a type(s) integer
2024-03-28T18:32:23.9991752Z error: final token list is invalid
```

**Comment by realshibadoge** [comment]
> Hey @realshibadoge, validation scripts are failling
> 
> ```
> 2024-03-28T18:32:23.9989382Z error: BURN: instance.decimals: is not of a type(s) integer
> 2024-03-28T18:32:23.9990660Z error: ShibDoge: instance.decimals: is not of a type(s) integer
> 2024-03-28T18:32:23.9991752Z error: final token list is invalid
> ```

Fixed. I used the base-migrate.xyz tool for this I will report back.

**Comment by realshibadoge** [comment]
I am mentioning @cfluke-cb as advised per Telegram instructions

**Comment by njokuScript** [comment]
> I am mentioning @cfluke-cb as advised per Telegram instructions

How come there's two token here? You're meant to create separate PRs for each token

**Comment by realshibadoge** [comment]
> > I am mentioning @cfluke-cb as advised per Telegram instructions
> 
> How come there's two token here? You're meant to create separate PRs for each token

I can remove one of them and open a separate PR if necessary. I just thought it could expedite the process.

**Comment by realshibadoge** [comment]
Updated to be single token. Other token issue opened here: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/753

**Comment by cfluke-cb** [comment]
Hi @realshibadoge How is the owner of the ethereum L1 contract managed? Currently this appears to be an EOA, is this owned by a single individual?

**Comment by realshibadoge** [comment]
> Hi @realshibadoge How is the owner of the ethereum L1 contract managed? Currently this appears to be an EOA, is this owned by a single individual?

It is a razor ledger. Is there a requirement for multisig that we have missed?

**Comment by realshibadoge** [comment]
Pinging @taycaldwell @wbnns for an update to this please 🙏

**Review by wbnns — APPROVED** [review]
ACK

**Review by annieke — APPROVED** [review]

**Pull request merged**
