### PR TITLE
Add IDRISS on Base to Superchain token list

### PR DESCRIPTION
**Pull request by lennardevertz**
IDRISS is an OptimismMintableERC20 token that also follows the SuperchainERC20 token standard. 

### Deployments
Natively deployed on Ethereum: [0x71b14F197DBB6b937665C78120fC07f8355c2C2C](https://etherscan.io/address/0x71b14f197dbb6b937665c78120fc07f8355c2c2c)
Bridged to Base: [0x000096630066820566162C94874A776532705231](https://basescan.org/address/0x000096630066820566162C94874A776532705231)

Coingecko token list submission pending.

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@lennardevertz 

Hi there! Thanks for opening this PR. CI/CD is currently failing with the below issue, please fix:
```
error: IDRISS on chain base token 0x000096630066820566162C94874A776532705231 could not fetch l2Bridge or l1Token.
This token most likely needs nobridge or a bridge override set.
```
See README for details.

**Comment by lennardevertz** [comment]
Gm @wbnns, thanks for the review. Interestingly the [OP bedrock IOptimismMintableERC20](https://github.com/ethereum-optimism/optimism/blob/80465cd6c428d13166fce351741492f354621643/packages/contracts-bedrock/src/universal/interfaces/IOptimismMintableERC20.sol) does not include the legacy `l1Token`, but only the  new `bridge` and `remoteToken` functions.
I added an overwrite for the bridge, how do we go about the `l1Token`?  The README doesn't mention that I can override it, but maybe it is already fixed through the bridge override. It is also the one mentioned in `data.tokens.ethereum.address`.

**Comment by wbnns** [comment]
@lennardevertz 

Thanks for the update; CI/CD is now passing; would you like to deploy and test on Sepolia/Base Sepolia first to make sure this is going to bridge as intended before implementing on mainnet? I would recommend this unless you would like to forgo doing so.

**Comment by lennardevertz** [comment]
Thanks!
We actually deployed and bridged this token a couple of times on testnet throughout the last weeks before deploying on mainnet. The links above show you the mainnet deployments including the correct bridge result from Ethereum to Base. So all good from our side!

**Review by wbnns — APPROVED** [review]
@lennardevertz 

Thanks for the updates and for building on Base 🔵

**Pull request merged**
