### PR TITLE
feat: Add Base L2 token address for Heroes of Mavia (MAVIA)

### PR DESCRIPTION
**Pull request by nhancv**

### CODE REVIEW

**Comment by Hmandalkar** [comment]
Hi @nhancv 
Can you please provide the following information for the [Onwer role](https://basescan.org/address/0x24fcFC492C1393274B6bcd568ac9e225BEc93584#readContract#F20) of the MAVIA contract:

1. The nature of any multi-sig or other custody setup (# signers required / total signers, or other guarded access). Please provide a link where this can be verified.
2. A claim indicating how many are independent signers (i.e. different individuals) there are - ideally please indicate the addresses of the multisig participants and the associated holder identities for those addresses. If this is not possible, can you please attest that these are separate entities?
3. Whether you use a hardware wallet, and if not where the keys are stored

**Comment by nhancv** [comment]
Hi Hmandalkar, 

Let me update:

1. It's is 2/6. You can verify this at https://app.safe.global/home?safe=base:0xd24934eEB0c65075f3E57A73144B82d8A4D45DE6

2. I'm afraid to share all the associated holder identities here but yes they are separate entities. 

3. The keys are encrypted and backed up to the cloud (Trust Wallet backup)


> Hi @nhancv Can you please provide the following information for the [Onwer role](https://basescan.org/address/0x24fcFC492C1393274B6bcd568ac9e225BEc93584#readContract#F20) of the MAVIA contract:
> 
>     1. The nature of any multi-sig or other custody setup (# signers required / total signers, or other guarded access). Please provide a link where this can be verified.
> 
>     2. A claim indicating how many are independent signers (i.e. different individuals) there are - ideally please indicate the addresses of the multisig participants and the associated holder identities for those addresses. If this is not possible, can you please attest that these are separate entities?
> 
>     3. Whether you use a hardware wallet, and if not where the keys are stored

**Review by wbnns — APPROVED** [review]
ACK

@nhancv Apologies, I'm sorry that you haven't received an update on this PR before today and thanks so much for your patience. 🙏

**Review by wbnns — CHANGES_REQUESTED** [review]
@nhancv 

In double-checking this PR I noted since this is non standard token, you'll need to add the `nonstandard=true` option. Please and this and then we'll re-review. 👍

**Comment by nhancv** [comment]
> @nhancv
> 
> In double-checking this PR I noted since this is non standard token, you'll need to add the `nonstandard=true` option. Please and this and then we'll re-review. 👍

I updated. Please check. Thank you.

**Review by wbnns — APPROVED** [review]
@nhancv 

Thanks!

**Review by annieke — APPROVED** [review]

**Pull request merged**
