### PR TITLE
Add Ambire Wallet to Base

### PR DESCRIPTION
**Pull request by stojnovsky**
**Description**

Added Ambire Wallet token address to the token list for the Base bridge.

@cfluke-cb @taycaldwell @wbnns

**Tests**

N/A

**Additional context**

N/A

**Metadata**

N/A

### CODE REVIEW

**Review by cfluke-cb — APPROVED** [review]
Looks good on Base side.

**Review by wbnns — CHANGES_REQUESTED** [review]
@stojnovsky 

Hi there! Could you please include the `nonstandard` option since the L1 isn't an ERC-20? https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#non-standard-tokens

**Comment by stojnovsky** [comment]
> @stojnovsky
> 
> Hi there! Could you please include the `nonstandard` option since the L1 isn't an ERC-20? https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#non-standard-tokens

Hey @wbnns, sure, we can do it, but could you elaborate more on what meant in those case for standard or not-standard ERC20?

**Comment by wbnns** [comment]
@stojnovsky 

Thanks! This signals in the metadata that the token isn't a standard ERC-20, which would be important information for integrators that it would potentially need to be reviewed and handled differently in their dapps.

**Comment by wbnns** [comment]
@stojnovsky Thanks for following up! Indeed, I can see in reviewing the code you have implemented the standard functions. This was not clear to me, I appreciate you confirming! No need to add the `nonstandard` option. 👍

**Review by wbnns — APPROVED** [review]
ACK

**Comment by stojnovsky** [comment]
> @stojnovsky Thanks for following up! Indeed, I can see in reviewing the code you have implemented the standard functions. This was not clear to me, I appreciate you confirming! No need to add the `nonstandard` option. 👍

@wbnns thanks for the support and for the quick responses

**Review by annieke — APPROVED** [review]

**Pull request merged**
