### PR TITLE
Add MUGLOO to Op 

### PR DESCRIPTION
**Pull request by raahulrathore**
**Description**

A cross chain token for my upcoming project implements IOptimismMintableERC20 for OpStack.

**Metadata**

Ethereum: [0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6](https://etherscan.io/address/0x8e3c68a9c10d3bf2aaf14f2e569a8223f21bf2b6)

Optimism: [~~0x2a7E178AD6b36f914D9E897f405a47A5E7609543~~](https://optimism.blockscout.com/address/0x2a7E178AD6b36f914D9E897f405a47A5E7609543) [0x1164b451624E0D53bD8Be84d3fF7f9591bA8922e](https://optimism.blockscout.com/address/0x1164b451624E0D53bD8Be84d3fF7f9591bA8922e)

updated contract as suggested in thread by @hamdiallam

### CODE REVIEW

**Comment by raahulrathore** [comment]
@nitaliano i see some test failed. please lemme know what can i do to get them fixed. Thanks!

**Comment by raahulrathore** [comment]
@hamdiallam just checking if any updates around this.

**Comment by hamdiallam** [comment]
ah @raahulrathore it looks like our validation script utilizes some of the legacy functions in `L2StandardERC20` in order to fetch l1/l2 token addresses.

I can push a fix soon and have you rebase this PR

**Comment by hamdiallam** [comment]
Unless you're set on this token address, if you extend `OptimismMintableERC20` instead of the interface, you'd inherit the legacy methods

See: https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/universal/OptimismMintableERC20.sol#L115

**Comment by raahulrathore** [comment]
@hamdiallam gotcha, will update with the suggested changes

**Comment by raahulrathore** [comment]
@hamdiallam do you want me to deploy a new contract with `OptimismMintableERC20` instead of `IOptimismMintableERC20 `(I can do that, if needed)
or should I just wait for your fixes in #916 and this PR automatically gets merged post that.

**Comment by hamdiallam** [comment]
> a new contract with `OptimismMintableERC20` instead of `IOptimismMintableERC20 `(I can do that, if needed)
> or should I just wait for your fixes in #916 and this PR automatically gets merged post that.

If you don't mind, a new contract would be the quickest route. Have to work through some updates with our contracts pnpm package

**Comment by raahulrathore** [comment]
sure @hamdiallam, will deploy a new contract and update the PR!

**Comment by raahulrathore** [comment]
> a new contract would be the quickest route

@hamdiallam done, can you please review and lemme know if any gaps.
Thanks!

**Comment by raahulrathore** [comment]
@hamdiallam just checking on this..

**Comment by hamdiallam** [comment]
Thanks for the bump @raahulrathore 

Looks great! Just wanted to double check I was looking at the verified [contract](https://optimism.blockscout.com/address/0x1164b451624E0D53bD8Be84d3fF7f9591bA8922e?tab=contract) on blockscout and it looks like the `OptimismMintableERC20` was directly deployed?

Asking because in the previous impl it looked like you wanted to disable burning (withdrawing) from L2 by overriding the burn function. Up to you but besides that looks good and can merge

**Comment by raahulrathore** [comment]
Ahn yes @hamdiallam 
I gave it a thought and thought while deploying the new contract to keep the burn function in place for future perspective.. So yea, will need the burn function with L2 being allowed to burn the tokens 
Good to go then @hamdiallam

**Comment by hamdiallam** [comment]
sounds good! @raahulrathore

**Review by hamdiallam — APPROVED** [review]

**Pull request merged**
