### PR TITLE
added Page Token information.

### PR DESCRIPTION
**Pull request by ipfsnut**
logo.svg included as well.

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@ipfsnut 

Hi there! Could you please verify your smart contract on Base?

https://basescan.org/address/0x748B45FdcA323D4AE510B82E323c5bEBCAbA41fB#code

**Comment by ipfsnut** [comment]
> @ipfsnut
> 
> Hi there! Could you please verify your smart contract on Base?
> 
> https://basescan.org/address/0x748B45FdcA323D4AE510B82E323c5bEBCAbA41fB#code

Apologies! I cannot. I had to simply remove it. If there's a proxy we can use to get 8 decimals on Base I am interested to find out about it.

**Comment by wbnns** [comment]
@ipfsnut You can use https://www.base-migrate.xyz/ 👍

**Comment by wbnns** [comment]
@ipfsnut 

Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

**Pull request closed without merging**
