### PR TITLE
MOCHI main and OP

### PR DESCRIPTION
**Pull request by oftenfrequent**
**Description**

Adding MOCHI tokens addresses for Mainnet and Optimism (replacing #269 due to validation issues)

**Tests**

I don't think I need tests for this sort of update

**Invariants**

No invariants here

**Additional context**

Can't wait to...
```py
                                         ^^
    ^^      ..                                       ..
            []                                       []
          .:[]:_          ^^                       ,:[]:.
        .: :[]: :-.                             ,-: :[]: :.
      .: : :[]: : :`._                       ,.': : :[]: : :.
    .: : : :[]: : : : :-._               _,-: : : : :[]: : : :.
_..: : : : :[]: : : : : : :-._________.-: : : : : : :[]: : : : :-._
_:_:_:_:_:_:[]:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:_:[]:_:_:_:_:_:_
!!!!!!!!!!!![]!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![]!!!!!!!!!!!!!
^^^^^^^^^^^^[]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[]^^^^^^^^^^^^^
            []                                       []
            []                                       []
            []                                       []
 ~~^-~^_~^~/  \~^-~^~_~^-~_^~-^~_^~~-^~_~^~-~_~-^~_^/  \~^-~_~^-~~-
~ _~~- ~^-^~-^~~- ^~_^-^~~_ -~^_ -~_-~~^- _~~_~-^_ ~^-^~~-_^-~ ~^
   ~ ^- _~~_-  ~~ _ ~  ^~  - ~~^ _ -  ^~-  ~ _  ~~^  - ~_   - ~^_~
     ~-  ^_  ~^ -  ^~ _ - ~^~ _   _~^~-  _ ~~^ - _ ~ - _ ~~^ -
jgs     ~^ -_ ~^^ -_ ~ _ - _ ~^~-  _~ -_   ~- _ ~^ _ -  ~ ^-
            ~^~ - _ ^ - ~~~ _ - _ ~-^ ~ __- ~_ - ~  ~^_-
                ~ ~- ^~ -  ~^ -  ~ ^~ - ~~  ^~ - ~
```

### CODE REVIEW

**Comment by oftenfrequent** [comment]
Hi, I am hoping to get this token on the bridge during the mid-week deploys. To do that, this needs to pass the validation check. I am able to [verify the mainnet token addresses](https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0xf134519cBE2042B06Ee7cE20Df51d09b55559896) successfully. Do I need to verify the L2 token as well? What am I missing to get this pulled in?

**Comment by oftenfrequent** [comment]
It appears as though the only item missing is presence on the CoinGecko token list. Is this a major blocker? I have since filled out a request to add Mochi to their list but it may take a few days

**Comment by zainbacchus** [comment]
Hi thank you for your PR! We'll review it and follow up this week!

**Comment by oftenfrequent** [comment]
@zainbacchus, for context, we were [awarded an OP grant](https://gov.optimism.io/t/review-gf-phase-1-mochi/3427) and are looking to deploy our contracts. In order to make that happen we need to bridge our tokens from mainnet.

**Comment by oftenfrequent** [comment]
Good news, we are [now listed on CoinGecko](https://www.coingecko.com/en/coins/mochi). Please let me know if there is anything else needed from us. We'd love to get on the bridge before this weekend!

**Comment by zainbacchus** [comment]
Thanks for the update! We review these weekly and will do our best to get this merged before the weekend :)

**Review by nickbalestra — APPROVED** [review]

**Pull request merged**
