### PR TITLE
add pndr token

### PR DESCRIPTION
**Pull request by benadamsky**
**Description**

PNDR tokens are automatically distributed each week for answering surveys on the official [survey Farcaster account](https://warpcast.com/survey) and can be used to deploy new surveys directly on the [Ponder website](https://www.weponder.io/surveys/create).

**Additional context**

Basescan creation tx: https://basescan.org/tx/0x5e2c3c2cc83db07a861a3c4e3aa5fb6a18256a3c2a4a0754d3db1281d383370a

### CODE REVIEW

**Comment by benadamsky** [comment]
@roberto-bayardo lmk if this looks good to go whenever you get the chance, thanks!

**Comment by benadamsky** [comment]
Hey @hamdiallam @roberto-bayardo any updates on this? Rolling out a big feature launch soon and want to make sure we're on the list before working with several partners.

Lmk if you need any additional info.

**Comment by cfluke-cb** [comment]
Hi Ben, this is in our pipeline for reviews this week. I'll try to keep you updated as it progresses

**Review by cfluke-cb — APPROVED** [review]

**Comment by cfluke-cb** [comment]
This is good from the base side

**Review by roninjin10 — APPROVED** [review]

**Pull request merged**
