### PR TITLE
Add LUSD Base Contract

### PR DESCRIPTION
**Pull request by abmisx0**
**Description**

Added LUSD Base Contract

**Tests**

I simply added a new token address for the Base bridged version of Mainnet LUSD.

**Additional context**

Basescan LUSD link:
https://basescan.org/token/0x368181499736d0c0cc614dbb145e2ec1ac86b8c6

Basescan LUSD deployment transaction:
https://basescan.org/tx/0x7148de4cfcb03469e313977a7ab123e8618d9a53b1882e733b97e7cc66966974

**Metadata**

N/A

### CODE REVIEW

**Comment by abmisx0** [comment]
@roberto-bayardo please review this PR when you got a chance

**Comment by abmisx0** [comment]
@roberto-bayardo this PR is stale now, please review when you can

**Review by roberto-bayardo — APPROVED** [review]

**Comment by roberto-bayardo** [comment]
looks good!

**Comment by abmisx0** [comment]
I see @ethereum-optimism/devxpod is a pending reviewer, can someone alert them please before this PR is closed.
@roberto-bayardo @roninjin10 pinging y'all for visibility

**Comment by roberto-bayardo** [comment]
@hamdiallam can you merge this?

**Review by roninjin10 — APPROVED** [review]

**Pull request merged**
