### PR TITLE
[Base] Add Brickken BKN

### PR DESCRIPTION
**Pull request by xaler5**
**Description**

Adding BKN - Brickken token to the Superchain token list.

Brickken enables businesses to create digital tokens backed by tokenized Real World Assets (RWA). Through the Token Suite, Clients can raise private or public capital by creating their own custom white-label token store & token offering. 
Capturing the whole token lifecycle, token issuers can also manage both their assets & investors under a seamless dashboard enabling cap table management, dividend distribution, and full investor - compliance.

**Tests**

It is not specified to add any tests in the following guide
https://github.com/ethereum-optimism/ethereum-optimism.github.io

**Additional context**

N/A

**Metadata**

N/A

Adding [@roberto-bayardo](https://github.com/roberto-bayardo) as reviewer as suggested in the guide

### CODE REVIEW

**Comment by xaler5** [comment]
It seems I can't really add specific reviewers to this PR as suggested in the guide, I already mentioned @roberto-bayardo in the description. Hope that's enough

**Comment by roninjin10** [comment]
Added base tag

**Comment by xaler5** [comment]
Since I saw that is [common](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/618#issuecomment-1894521799) question made by @GabrielaMelendezQuan I can provide the info beforehand so we can hopefully make the review process faster:

BKN on Ethereum mainnet was permissioned in the sense that it had a minter role, a burner role and a default admin role. On Base, the BKN token has been deployed through the official Base factory without any extra roles and on BSC the BKN token has been deployed through the Wormhole portal bridge without extra roles neither. 

- MINTER_ROLE has been renounced in [this](https://etherscan.io/tx/0x5be22e07f3f62b3e02d44056b4327b63e9f0b2b4a80479c7ee4037ddf5c23d3c) tx

We still have the burner role that is maintained by our [multisig](https://etherscan.io/address/0x65b9ef846e9989c481c40c01cb7f128ebf892916) whose configuration can be entirely seen on chain.

**Comment by xaler5** [comment]
The token is also verified now on [basescan](https://basescan.org/token/0xddB293BB5C5258F7484A94a0fBd5c8B2F6E4e376), a part from being already verified on etherscan and bscscan

**Comment by xaler5** [comment]
Does [this](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/634) PR affects the current one ?

**Comment by roberto-bayardo** [comment]
I'm hoping that PR will allow validation to pass. For some reason I can't seem to re-run the validation. cc @hamdiallam

**Comment by xaler5** [comment]
done @hamdiallam

**Comment by hamdiallam** [comment]
great, it's passing now. Just need an approval from base cc @roberto-bayardo

**Comment by xaler5** [comment]
@roberto-bayardo is there any blocker left ? Happy to help

**Review by cfluke-cb — APPROVED** [review]
looks good on base side

**Review by spacesailor24 — APPROVED** [review]

**Pull request merged**
