### PR TITLE
Hoge2.0 Metadata

### PR DESCRIPTION
**Pull request by hoge-rileous**
Metadata for HOGE Finance. Wrapped on ETH (to a standard tax-free ERC-20) and then bridged via Optimism standard contracts.

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@hoge-rileous 

Heya! Thanks for the PR! Can you please make sure the deployed L1 and L2 contracts have the same name and symbol?

It is a standard convention that they remain the same.

**Comment by hoge-rileous** [comment]
@wbnns 
Thank you for checking. We re-deployed to make the name and symbol consistent.

**Review by wbnns — APPROVED** [review]
ACK

**Review by wbnns — CHANGES_REQUESTED** [review]
@hoge-rileous 

Can you please resolve these to CI issues?
```
error: HOGE2.0 on chain ethereum token 0x25699C4b6bbF148A8FDb4b5823e8D9BbA44C8090 has incorrect decimals
warning: HOGE2.0 on chain ethereum token 0x25699C4b6bbF148A8FDb4b5823e8D9BbA44C8090 not found on CoinGecko token list
```

**Comment by hoge-rileous** [comment]
@wbnns is it possible to override decimals on the different chains? Or override the standard token's default value? Please advise. Thank you

**Comment by wbnns** [comment]
@hoge-rileous 

Heya, no, it's not possible override the decimals but you can redploy on Base using this contract to ensure the decimals match L1. 👍

Here's the factory contract you can use: https://basescan.org/address/0xF10122D428B4bc8A9d050D06a2037259b4c4B83B#code

**Comment by wbnns** [comment]
@hoge-rileous 

Since it's been a while and we haven't heard back, closing this for now. Please let us know if you'd like to pursue the additional changes to resolve the outstanding issues on the PR and we can reopen. 👍

**Pull request closed without merging**
