### PR TITLE
Updated SCM (added base address)

### PR DESCRIPTION
**Pull request by voenkomatiwe**
Greetings @roberto-bayardo. In this PR I added [Base token address](https://basescan.org/token/0x05bf2896fcbafb51873f1221da3c6ec9ebd4554c).

### CODE REVIEW

**Comment by roberto-bayardo** [comment]
Thanks, can you verify the token contracts? Seems all we can view is the proxy part of it.

**Comment by ars9** [comment]
@roberto-bayardo We used portalbridge to bridge the tokens initially and it doesn't seem to support contract verification. What can we do about it?

**Comment by voenkomatiwe** [comment]
I have added changes, please look again @roberto-bayardo.

**Comment by roberto-bayardo** [comment]
Still appears as unverified... looks like your optimism contract is however, do you know how you were able to verify it there?

**Comment by ericm-cb** [comment]
Hey guys, if you're running into verification issues, I'd recommend flattening the entire contract and try having BaseScan verify that.

**Comment by ars9** [comment]
@ericm-cb That's the problem. We have no idea what contract is deployed there by Wormhole and what were constructor arguments.

**Review by hamdiallam — COMMENTED** [review]
Hi, it looks like the Base version of this token isn't bridged by the StandardBridge contract. Is there a reason for this discrepancy between Optimism & Base?

**Comment by ars9** [comment]
@hamdiallam We've used Wormhole to bridge to Base and manual deployment via standard contract for Optimism.

**Comment by ericm-cb** [comment]
Hey @ars9, are you guys able to redeploy this without using the wormhole bridge at all or would that mess up your guys' intended architecture? We recommend all Base bridge tokens be deployed using our [factory contract](https://basescan.org/address/0xf23d369d7471bd9f6487e198723eea023389f1d4). 

Unfortunately without being able to see the verified proxy and implementation contracts, we can't properly approve. Other wormhole bridge tokens have been generated/verified successfully so I'm wondering if there was an issue during the creation of your token.

**Review by roninjin10 — CHANGES_REQUESTED** [review]
Need to deploy with standard bridge

**Pull request closed without merging**
