### PR TITLE
Add CHI token

### PR DESCRIPTION
**Pull request by dusan-mrsic**
Token name and symbol is CHI. It is added in CHI-PROTOCOL folder because there is already CHI folder in project.

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@dusan-mrsic 

Hi there! CI is failing with the following issue:
```
error: CHI-PROTOCOL on chain base token 0x3b21418081528845a6DF4e970bD2185545b712ba could not fetch l2Bridge or l1Token.

This token most likely needs nobridge or a bridge override set.
```
Could you please fix and update the PR?

**Comment by dusan-mrsic** [comment]
Hi @wbnns , can the problem be with the name? Because symbol is CHI, but folder name is CHI-PROTOCOL, but I didn't know what to put because there is already CHI folder?

**Comment by wbnns** [comment]
@dusan-mrsic 

Heya, hm, yeah -- let's loop in @annieke or @hamdiallam here. 🤔

**Comment by hamdiallam** [comment]
Hey @dusan-mrsic, this error isn't due to the name but due to the contract itself.

How is this token bridged from L1, through the standard bridge contracts? If so it's not a proper `OptimismMintableERC20`. I would recommend not extending the interface but the concrete [contract](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/universal/OptimismMintableERC20.sol). Then supply the appropriate constructor arguments

**Comment by wbnns** [comment]
@dusan-mrsic 

Will close this PR for now. Please let us know if you'd like to pursue this change and we can reopen. 👍

**Comment by dusan-mrsic** [comment]
@wbnns @hamdiallam But why this is the problem? It is extending IOptimismMintableERC20. Our token USC is the same as this one and it is merged without problems.

**Pull request closed without merging**
