### PR TITLE
Add SMT token support to the Optimism network

### PR DESCRIPTION
**Pull request by b0gdaniy**
**Description**

Add SMT token support to the Optimism network.
Token Ethereum Mainnet address: https://etherscan.io/address/0xB17548c7B510427baAc4e267BEa62e800b247173
Token Optimism Mainnet address: https://optimistic.etherscan.io/address/0x8Eb99a441b04576282e9069977F6DE6053EF6a97

**Tests**

Tests are not provided as the contract has been deployed by the [OptimismMintableERC20Factory](https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000012).

**Additional context**

No additional context.

**Metadata**

N/A

### CODE REVIEW

**Comment by annieke** [comment]
hey @b0gdaniy ! can you rebase this PR?

**Comment by b0gdaniy** [comment]
> hey @b0gdaniy ! can you rebase this PR?

Hello @annieke, done)

**Comment by b0gdaniy** [comment]
@annieke @hamdiallam can you please check?

**Review by hamdiallam — APPROVED** [review]

**Comment by hamdiallam** [comment]
Sorry for the delay! got lost in the sea of PRs

**Pull request merged**
