### PR TITLE
Add base address of TETU

### PR DESCRIPTION
**Pull request by belbix**
Info about TETU token.

Coingecko info about the mainnet token is not available yet. It should be added soon.
https://www.coingecko.com/en/coins/tetu

Our token is minted on Polygon and we migrated to the native Polygon bridge after the Multichain incident.

### CODE REVIEW

**Comment by belbix** [comment]
Please add [@roberto-bayardo](https://github.com/roberto-bayardo) to reviewers

**Comment by belbix** [comment]
hey guys!
do you need anything from my side?
how I can contact @roberto-bayardo?

**Comment by roberto-bayardo** [comment]
apologies taking a look

**Comment by roberto-bayardo** [comment]
Looks good from base side cc @roninjin10

**Review by spacesailor24 — APPROVED** [review]

**Comment by belbix** [comment]
thanks a lot for merging!
when TETU token will be showed on the bridge UI?
does it require any actions from our side?

**Pull request merged**
